name: AWS credentials
description: Assume a role via OIDC.

inputs:
  role-to-assume:
    description: ARN of the role to assume.
    required: true
  aws-region:
    description: Region to assume the role in.
    required: true

runs:
  using: composite
  steps:
    - uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6.2.4
      with:
        role-to-assume: ${{ inputs.role-to-assume }}
        aws-region: ${{ inputs.aws-region }}
