// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `SelectDesiredDeployments`. */
export interface ISelectDesiredDeploymentsResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    state: import("@repo/protocol").AppState;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectDesiredVolumes`. */
export interface ISelectDesiredVolumesResult {
    app_id: import("@repo/protocol").AppId;
    state: import("@repo/protocol").AppState;
}

/** Result of query `SelectDesiredHostnames`. */
export interface ISelectDesiredHostnamesResult {
    app_id: import("@repo/protocol").AppId;
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectDesiredExports`. */
export interface ISelectDesiredExportsResult {
    id: import("@repo/protocol").ExportId;
    app_id: import("@repo/protocol").AppId;
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: import("@repo/protocol").ObjectKey;
    state: import("@repo/protocol").ExportState;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    artifact_object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
}

/** Result of query `SelectAppOwnership`. */
export interface ISelectAppOwnershipResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `InsertApp`. */
export interface IInsertAppResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `InsertAppConfig`. */
export interface IInsertAppConfigResult {
}

/** Result of query `InsertAppHostname`. */
export interface IInsertAppHostnameResult {
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectCreatedApp`. */
export interface ISelectCreatedAppResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppsByOwner`. */
export interface ISelectAppsByOwnerResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppHostnamesByOwner`. */
export interface ISelectAppHostnamesByOwnerResult {
    app_id: import("@repo/protocol").AppId;
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectAppById`. */
export interface ISelectAppByIdResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppHostnamesByApp`. */
export interface ISelectAppHostnamesByAppResult {
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectAppForConfigUpdate`. */
export interface ISelectAppForConfigUpdateResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `SelectCurrentAppConfig`. */
export interface ISelectCurrentAppConfigResult {
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `InsertPatchedAppConfig`. */
export interface IInsertPatchedAppConfigResult {
    id: string;
}

/** Result of query `TouchAppAfterConfigPatch`. */
export interface ITouchAppAfterConfigPatchResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectFinishableDeletion`. */
export interface ISelectFinishableDeletionResult {
    app_id: import("@repo/protocol").AppId;
}

/** Result of query `SelectFinishableDeletions`. */
export interface ISelectFinishableDeletionsResult {
    app_id: import("@repo/protocol").AppId;
}

/** Result of query `FinishDeletingApp`. */
export interface IFinishDeletingAppResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `SelectPurgeableApps`. */
export interface ISelectPurgeableAppsResult {
    app_id: import("@repo/protocol").AppId;
}

/** Result of query `SelectUnsharedArtifactKeys`. */
export interface ISelectUnsharedArtifactKeysResult {
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
}

/** Result of query `SelectExportKeysByApp`. */
export interface ISelectExportKeysByAppResult {
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: import("@repo/protocol").ObjectKey;
}

/** Result of query `DeleteExportsByApp`. */
export interface IDeleteExportsByAppResult {
}

/** Result of query `DeleteDeploymentsByApp`. */
export interface IDeleteDeploymentsByAppResult {
}

/** Result of query `DeleteArtifactsByApp`. */
export interface IDeleteArtifactsByAppResult {
}

/** Result of query `UpdateAppState`. */
export interface IUpdateAppStateResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `SelectAppAfterStateChange`. */
export interface ISelectAppAfterStateChangeResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `InsertArtifact`. */
export interface IInsertArtifactResult {
    id: import("@repo/protocol").ArtifactId;
    app_id: import("@repo/protocol").AppId;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    created_at: Date;
}

/** Result of query `SelectArtifactsByApp`. */
export interface ISelectArtifactsByAppResult {
    id: import("@repo/protocol").ArtifactId;
    app_id: import("@repo/protocol").AppId;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    created_at: Date;
}

/** Result of query `SelectArtifactById`. */
export interface ISelectArtifactByIdResult {
    id: import("@repo/protocol").ArtifactId;
    app_id: import("@repo/protocol").AppId;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    created_at: Date;
}

/** Result of query `SelectDeployableArtifact`. */
export interface ISelectDeployableArtifactResult {
    id: import("@repo/protocol").ArtifactId;
}

/** Result of query `InsertDeployment`. */
export interface IInsertDeploymentResult {
    id: import("@repo/protocol").DeploymentId;
}

/** Result of query `SelectDeploymentToReplay`. */
export interface ISelectDeploymentToReplayResult {
    id: import("@repo/protocol").DeploymentId;
}

/** Result of query `InsertReplayedDeployment`. */
export interface IInsertReplayedDeploymentResult {
    id: import("@repo/protocol").DeploymentId;
}

/** Result of query `SelectDeploymentsByApp`. */
export interface ISelectDeploymentsByAppResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    state: import("@repo/protocol").DeploymentState;
    activated_at: Date | null;
    /** The deployment this one replays, when it was made to go back to one. */
    rollback_of_deployment_id: import("@repo/protocol").DeploymentId | null;
    created_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectDeploymentById`. */
export interface ISelectDeploymentByIdResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    state: import("@repo/protocol").DeploymentState;
    activated_at: Date | null;
    /** The deployment this one replays, when it was made to go back to one. */
    rollback_of_deployment_id: import("@repo/protocol").DeploymentId | null;
    created_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectLiveDeployments`. */
export interface ISelectLiveDeploymentsResult {
    id: import("@repo/protocol").DeploymentId;
    state: import("@repo/protocol").DeploymentState;
    created_at: Date;
    desired_running: boolean;
}

/** Result of query `ApplyReportedDeployment`. */
export interface IApplyReportedDeploymentResult {
}

/** Result of query `StampDeploymentActivation`. */
export interface IStampDeploymentActivationResult {
}

/** Result of query `FailDeployment`. */
export interface IFailDeploymentResult {
}

/** Result of query `SupersedeLiveDeployment`. */
export interface ISupersedeLiveDeploymentResult {
}

/** Result of query `SelectInsertedDeployment`. */
export interface ISelectInsertedDeploymentResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    state: import("@repo/protocol").DeploymentState;
    activated_at: Date | null;
    /** The deployment this one replays, when it was made to go back to one. */
    rollback_of_deployment_id: import("@repo/protocol").DeploymentId | null;
    created_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `InsertExport`. */
export interface IInsertExportResult {
    id: import("@repo/protocol").ExportId;
}

/** Result of query `SelectExportsByApp`. */
export interface ISelectExportsByAppResult {
    id: import("@repo/protocol").ExportId;
    app_id: import("@repo/protocol").AppId;
    state: import("@repo/protocol").ExportState;
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: import("@repo/protocol").ObjectKey;
    size_bytes: string | null;
    /** Why the export is in the state it is in, as the host put it. Never the tenant's own output. */
    message: string | null;
    ready_at: Date | null;
    /** When the bucket's lifecycle rule removes the bundle. The api refuses to sign past it. */
    expires_at: Date;
    created_at: Date;
    app_slug: import("@repo/protocol").DnsLabel;
}

/** Result of query `SelectExportById`. */
export interface ISelectExportByIdResult {
    id: import("@repo/protocol").ExportId;
    app_id: import("@repo/protocol").AppId;
    state: import("@repo/protocol").ExportState;
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: import("@repo/protocol").ObjectKey;
    size_bytes: string | null;
    /** Why the export is in the state it is in, as the host put it. Never the tenant's own output. */
    message: string | null;
    ready_at: Date | null;
    /** When the bucket's lifecycle rule removes the bundle. The api refuses to sign past it. */
    expires_at: Date;
    created_at: Date;
    app_slug: import("@repo/protocol").DnsLabel;
}

/** Result of query `ApplyReportedExport`. */
export interface IApplyReportedExportResult {
}

/** Result of query `FailInFlightExports`. */
export interface IFailInFlightExportsResult {
}

/** Result of query `SelectInFlightExport`. */
export interface ISelectInFlightExportResult {
    id: import("@repo/protocol").ExportId;
    app_id: import("@repo/protocol").AppId;
    state: import("@repo/protocol").ExportState;
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: import("@repo/protocol").ObjectKey;
    size_bytes: string | null;
    /** Why the export is in the state it is in, as the host put it. Never the tenant's own output. */
    message: string | null;
    ready_at: Date | null;
    /** When the bucket's lifecycle rule removes the bundle. The api refuses to sign past it. */
    expires_at: Date;
    created_at: Date;
    app_slug: import("@repo/protocol").DnsLabel;
}

/** Result of query `SelectHealthPing`. */
export interface ISelectHealthPingResult {
    ok: number | null;
}

export interface Queries {
    SelectDesiredDeployments: ISelectDesiredDeploymentsResult;
    SelectDesiredVolumes: ISelectDesiredVolumesResult;
    SelectDesiredHostnames: ISelectDesiredHostnamesResult;
    SelectDesiredExports: ISelectDesiredExportsResult;
    SelectAppOwnership: ISelectAppOwnershipResult;
    InsertApp: IInsertAppResult;
    InsertAppConfig: IInsertAppConfigResult;
    InsertAppHostname: IInsertAppHostnameResult;
    SelectCreatedApp: ISelectCreatedAppResult;
    SelectAppsByOwner: ISelectAppsByOwnerResult;
    SelectAppHostnamesByOwner: ISelectAppHostnamesByOwnerResult;
    SelectAppById: ISelectAppByIdResult;
    SelectAppHostnamesByApp: ISelectAppHostnamesByAppResult;
    SelectAppForConfigUpdate: ISelectAppForConfigUpdateResult;
    SelectCurrentAppConfig: ISelectCurrentAppConfigResult;
    InsertPatchedAppConfig: IInsertPatchedAppConfigResult;
    TouchAppAfterConfigPatch: ITouchAppAfterConfigPatchResult;
    SelectFinishableDeletion: ISelectFinishableDeletionResult;
    SelectFinishableDeletions: ISelectFinishableDeletionsResult;
    FinishDeletingApp: IFinishDeletingAppResult;
    SelectPurgeableApps: ISelectPurgeableAppsResult;
    SelectUnsharedArtifactKeys: ISelectUnsharedArtifactKeysResult;
    SelectExportKeysByApp: ISelectExportKeysByAppResult;
    DeleteExportsByApp: IDeleteExportsByAppResult;
    DeleteDeploymentsByApp: IDeleteDeploymentsByAppResult;
    DeleteArtifactsByApp: IDeleteArtifactsByAppResult;
    UpdateAppState: IUpdateAppStateResult;
    SelectAppAfterStateChange: ISelectAppAfterStateChangeResult;
    InsertArtifact: IInsertArtifactResult;
    SelectArtifactsByApp: ISelectArtifactsByAppResult;
    SelectArtifactById: ISelectArtifactByIdResult;
    SelectDeployableArtifact: ISelectDeployableArtifactResult;
    InsertDeployment: IInsertDeploymentResult;
    SelectDeploymentToReplay: ISelectDeploymentToReplayResult;
    InsertReplayedDeployment: IInsertReplayedDeploymentResult;
    SelectDeploymentsByApp: ISelectDeploymentsByAppResult;
    SelectDeploymentById: ISelectDeploymentByIdResult;
    SelectLiveDeployments: ISelectLiveDeploymentsResult;
    ApplyReportedDeployment: IApplyReportedDeploymentResult;
    StampDeploymentActivation: IStampDeploymentActivationResult;
    FailDeployment: IFailDeploymentResult;
    SupersedeLiveDeployment: ISupersedeLiveDeploymentResult;
    SelectInsertedDeployment: ISelectInsertedDeploymentResult;
    InsertExport: IInsertExportResult;
    SelectExportsByApp: ISelectExportsByAppResult;
    SelectExportById: ISelectExportByIdResult;
    ApplyReportedExport: IApplyReportedExportResult;
    FailInFlightExports: IFailInFlightExportsResult;
    SelectInFlightExport: ISelectInFlightExportResult;
    SelectHealthPing: ISelectHealthPingResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
