// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `InsertApp`. */
export interface IInsertAppResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `InsertAppConfig`. */
export interface IInsertAppConfigResult {
}

/** Result of query `InsertAppHostname`. */
export interface IInsertAppHostnameResult {
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectCreatedApp`. */
export interface ISelectCreatedAppResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppsByOwner`. */
export interface ISelectAppsByOwnerResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppHostnamesByOwner`. */
export interface ISelectAppHostnamesByOwnerResult {
    app_id: import("@repo/protocol").AppId;
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectAppById`. */
export interface ISelectAppByIdResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppHostnamesByApp`. */
export interface ISelectAppHostnamesByAppResult {
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectAppForConfigUpdate`. */
export interface ISelectAppForConfigUpdateResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `SelectCurrentAppConfig`. */
export interface ISelectCurrentAppConfigResult {
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `InsertPatchedAppConfig`. */
export interface IInsertPatchedAppConfigResult {
    id: string | null;
}

/** Result of query `TouchAppAfterConfigPatch`. */
export interface ITouchAppAfterConfigPatchResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `UpdateAppState`. */
export interface IUpdateAppStateResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `SelectAppAfterStateChange`. */
export interface ISelectAppAfterStateChangeResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectHealthPing`. */
export interface ISelectHealthPingResult {
    ok: number | null;
}

export interface Queries {
    InsertApp: IInsertAppResult;
    InsertAppConfig: IInsertAppConfigResult;
    InsertAppHostname: IInsertAppHostnameResult;
    SelectCreatedApp: ISelectCreatedAppResult;
    SelectAppsByOwner: ISelectAppsByOwnerResult;
    SelectAppHostnamesByOwner: ISelectAppHostnamesByOwnerResult;
    SelectAppById: ISelectAppByIdResult;
    SelectAppHostnamesByApp: ISelectAppHostnamesByAppResult;
    SelectAppForConfigUpdate: ISelectAppForConfigUpdateResult;
    SelectCurrentAppConfig: ISelectCurrentAppConfigResult;
    InsertPatchedAppConfig: IInsertPatchedAppConfigResult;
    TouchAppAfterConfigPatch: ITouchAppAfterConfigPatchResult;
    UpdateAppState: IUpdateAppStateResult;
    SelectAppAfterStateChange: ISelectAppAfterStateChangeResult;
    SelectHealthPing: ISelectHealthPingResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
