// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `SelectAppOwnership`. */
export interface ISelectAppOwnershipResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `InsertApp`. */
export interface IInsertAppResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `InsertAppConfig`. */
export interface IInsertAppConfigResult {
}

/** Result of query `InsertAppHostname`. */
export interface IInsertAppHostnameResult {
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectCreatedApp`. */
export interface ISelectCreatedAppResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppsByOwner`. */
export interface ISelectAppsByOwnerResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppHostnamesByOwner`. */
export interface ISelectAppHostnamesByOwnerResult {
    app_id: import("@repo/protocol").AppId;
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectAppById`. */
export interface ISelectAppByIdResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppHostnamesByApp`. */
export interface ISelectAppHostnamesByAppResult {
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectAppForConfigUpdate`. */
export interface ISelectAppForConfigUpdateResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `SelectCurrentAppConfig`. */
export interface ISelectCurrentAppConfigResult {
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `InsertPatchedAppConfig`. */
export interface IInsertPatchedAppConfigResult {
    id: string | null;
}

/** Result of query `TouchAppAfterConfigPatch`. */
export interface ITouchAppAfterConfigPatchResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `UpdateAppState`. */
export interface IUpdateAppStateResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `SelectAppAfterStateChange`. */
export interface ISelectAppAfterStateChangeResult {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    created_at: Date;
    updated_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `InsertArtifact`. */
export interface IInsertArtifactResult {
    id: import("@repo/protocol").ArtifactId;
    app_id: import("@repo/protocol").AppId;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    created_at: Date;
}

/** Result of query `SelectArtifactsByApp`. */
export interface ISelectArtifactsByAppResult {
    id: import("@repo/protocol").ArtifactId;
    app_id: import("@repo/protocol").AppId;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    created_at: Date;
}

/** Result of query `SelectArtifactById`. */
export interface ISelectArtifactByIdResult {
    id: import("@repo/protocol").ArtifactId;
    app_id: import("@repo/protocol").AppId;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    created_at: Date;
}

/** Result of query `SelectDeployableApp`. */
export interface ISelectDeployableAppResult {
    id: import("@repo/protocol").AppId;
}

/** Result of query `SupersedeLiveDeployment`. */
export interface ISupersedeLiveDeploymentResult {
}

/** Result of query `InsertDeployment`. */
export interface IInsertDeploymentResult {
    id: import("@repo/protocol").DeploymentId;
}

/** Result of query `SelectInsertedDeployment`. */
export interface ISelectInsertedDeploymentResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    state: import("@repo/protocol").DeploymentState;
    activated_at: Date | null;
    created_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectDeploymentsByApp`. */
export interface ISelectDeploymentsByAppResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    state: import("@repo/protocol").DeploymentState;
    activated_at: Date | null;
    created_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectDeploymentById`. */
export interface ISelectDeploymentByIdResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    state: import("@repo/protocol").DeploymentState;
    activated_at: Date | null;
    created_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SupersedeReplacedDeployment`. */
export interface ISupersedeReplacedDeploymentResult {
}

/** Result of query `RunDeployment`. */
export interface IRunDeploymentResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    state: import("@repo/protocol").DeploymentState;
    activated_at: Date | null;
    created_at: Date;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `UpdateDeploymentFromReport`. */
export interface IUpdateDeploymentFromReportResult {
}

/** Result of query `SelectDesiredStateGeneration`. */
export interface ISelectDesiredStateGenerationResult {
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    generation: string;
}

/** Result of query `SelectRunningDeployments`. */
export interface ISelectRunningDeploymentsResult {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    digest: import("@repo/protocol").Sha256Digest;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string;
    /** Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    guest_port: import("@repo/protocol").GuestPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
}

/** Result of query `SelectAppVolumes`. */
export interface ISelectAppVolumesResult {
    id: import("@repo/protocol").AppId;
    state: import("@repo/protocol").AppState;
}

/** Result of query `SelectDeployedHostnames`. */
export interface ISelectDeployedHostnamesResult {
    app_id: import("@repo/protocol").AppId;
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
}

/** Result of query `SelectHealthPing`. */
export interface ISelectHealthPingResult {
    ok: number | null;
}

export interface Queries {
    SelectAppOwnership: ISelectAppOwnershipResult;
    InsertApp: IInsertAppResult;
    InsertAppConfig: IInsertAppConfigResult;
    InsertAppHostname: IInsertAppHostnameResult;
    SelectCreatedApp: ISelectCreatedAppResult;
    SelectAppsByOwner: ISelectAppsByOwnerResult;
    SelectAppHostnamesByOwner: ISelectAppHostnamesByOwnerResult;
    SelectAppById: ISelectAppByIdResult;
    SelectAppHostnamesByApp: ISelectAppHostnamesByAppResult;
    SelectAppForConfigUpdate: ISelectAppForConfigUpdateResult;
    SelectCurrentAppConfig: ISelectCurrentAppConfigResult;
    InsertPatchedAppConfig: IInsertPatchedAppConfigResult;
    TouchAppAfterConfigPatch: ITouchAppAfterConfigPatchResult;
    UpdateAppState: IUpdateAppStateResult;
    SelectAppAfterStateChange: ISelectAppAfterStateChangeResult;
    InsertArtifact: IInsertArtifactResult;
    SelectArtifactsByApp: ISelectArtifactsByAppResult;
    SelectArtifactById: ISelectArtifactByIdResult;
    SelectDeployableApp: ISelectDeployableAppResult;
    SupersedeLiveDeployment: ISupersedeLiveDeploymentResult;
    InsertDeployment: IInsertDeploymentResult;
    SelectInsertedDeployment: ISelectInsertedDeploymentResult;
    SelectDeploymentsByApp: ISelectDeploymentsByAppResult;
    SelectDeploymentById: ISelectDeploymentByIdResult;
    SupersedeReplacedDeployment: ISupersedeReplacedDeploymentResult;
    RunDeployment: IRunDeploymentResult;
    UpdateDeploymentFromReport: IUpdateDeploymentFromReportResult;
    SelectDesiredStateGeneration: ISelectDesiredStateGenerationResult;
    SelectRunningDeployments: ISelectRunningDeploymentsResult;
    SelectAppVolumes: ISelectAppVolumesResult;
    SelectDeployedHostnames: ISelectDeployedHostnamesResult;
    SelectHealthPing: ISelectHealthPingResult;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
}

export {};
