// @generated by bun-sqlgen — do not edit.
// Run the generator to refresh.

/** Result of query `SelectDesiredDeployments`. */
export interface ISelectDesiredDeploymentsResult {
    id: IDeploymentsColumns["id"];
    app_id: IDeploymentsColumns["app_id"];
    state: IAppsColumns["state"];
    /** Absent until the api has hashed the uploaded object; its presence is what makes the row an artifact. */
    digest: NonNullable<IArtifactsColumns["digest"]>;
    /** Counted off the uploaded bytes, so absent until they are there. A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: NonNullable<IArtifactsColumns["size_bytes"]>;
    /** Where the verified bytes came to rest, so absent while they are still in a staging slot. Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: NonNullable<IArtifactsColumns["object_key"]>;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: IArtifactsColumns["original_file_name"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    /** The app config version this deployment was launched with. */
    config_id: IDeploymentsColumns["config_id"];
    activation: IAppsColumns["activation"];
    idle_timeout_ms: IAppsColumns["idle_timeout_ms"];
}

/** Result of query `SelectDesiredVolumes`. */
export interface ISelectDesiredVolumesResult {
    app_id: IAppsColumns["id"];
    state: IAppsColumns["state"];
}

/** Result of query `SelectDesiredHostnames`. */
export interface ISelectDesiredHostnamesResult {
    app_id: IAppHostnamesColumns["app_id"];
    hostname: IAppHostnamesColumns["hostname"];
    kind: IAppHostnamesColumns["kind"];
}

/** Result of query `SelectDesiredEnvironment`. */
export interface ISelectDesiredEnvironmentResult {
    deployment_id: IDeploymentsColumns["id"];
    name: IAppConfigEnvironmentColumns["name"];
    /** Sealed by the api before it arrives. Never written or read in the clear. */
    value: IAppConfigEnvironmentColumns["value"];
}

/** Result of query `SelectDesiredExports`. */
export interface ISelectDesiredExportsResult {
    id: IExportsColumns["id"];
    app_id: IExportsColumns["app_id"];
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: IExportsColumns["object_key"];
    state: IExportsColumns["state"];
    /** Absent until the api has hashed the uploaded object; its presence is what makes the row an artifact. */
    digest: NonNullable<IArtifactsColumns["digest"]>;
    /** Counted off the uploaded bytes, so absent until they are there. A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: NonNullable<IArtifactsColumns["size_bytes"]>;
    /** Where the verified bytes came to rest, so absent while they are still in a staging slot. Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    artifact_object_key: NonNullable<IArtifactsColumns["object_key"]>;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: IArtifactsColumns["original_file_name"];
    /** The config version whose environment belongs in the bundle, pinned when the export was asked for. */
    config_id: IExportsColumns["config_id"];
}

/** Result of query `SelectDesiredExportEnvironment`. */
export interface ISelectDesiredExportEnvironmentResult {
    export_id: IExportsColumns["id"];
    name: IAppConfigEnvironmentColumns["name"];
    /** Sealed by the api before it arrives. Never written or read in the clear. */
    value: IAppConfigEnvironmentColumns["value"];
}

/** Result of query `SelectAppHostnamesByOwner`. */
export interface ISelectAppHostnamesByOwnerResult {
    app_id: IAppHostnamesColumns["app_id"];
    hostname: IAppHostnamesColumns["hostname"];
    kind: IAppHostnamesColumns["kind"];
    state: IAppHostnamesColumns["state"];
    /** What the owner points _acme-challenge at, so the edge can renew the certificate without asking them again. Absent for a platform hostname. */
    dcv_target: IAppHostnamesColumns["dcv_target"];
}

/** Result of query `SelectAppHostnamesByApp`. */
export interface ISelectAppHostnamesByAppResult {
    hostname: IAppHostnamesColumns["hostname"];
    kind: IAppHostnamesColumns["kind"];
    state: IAppHostnamesColumns["state"];
    /** What the owner points _acme-challenge at, so the edge can renew the certificate without asking them again. Absent for a platform hostname. */
    dcv_target: IAppHostnamesColumns["dcv_target"];
}

/** Result of query `InsertCustomAppHostname`. */
export interface IInsertCustomAppHostnameResult {
    hostname: IAppHostnamesColumns["hostname"];
    kind: IAppHostnamesColumns["kind"];
    state: IAppHostnamesColumns["state"];
    /** What the owner points _acme-challenge at, so the edge can renew the certificate without asking them again. Absent for a platform hostname. */
    dcv_target: IAppHostnamesColumns["dcv_target"];
}

/** Result of query `UpdateCustomAppHostnameEdge`. */
export interface IUpdateCustomAppHostnameEdgeResult {
    hostname: IAppHostnamesColumns["hostname"];
    kind: IAppHostnamesColumns["kind"];
    state: IAppHostnamesColumns["state"];
    /** What the owner points _acme-challenge at, so the edge can renew the certificate without asking them again. Absent for a platform hostname. */
    dcv_target: IAppHostnamesColumns["dcv_target"];
}

/** Result of query `UpdateCustomAppHostnameState`. */
export interface IUpdateCustomAppHostnameStateResult {
    hostname: IAppHostnamesColumns["hostname"];
}

/** Result of query `DeleteCustomAppHostname`. */
export interface IDeleteCustomAppHostnameResult {
    /** The custom hostname this row is projected onto at the edge. Absent for a platform hostname, which the wildcard already covers. */
    cloudflare_id: IAppHostnamesColumns["cloudflare_id"];
}

/** Result of query `SelectPendingCustomHostnames`. */
export interface ISelectPendingCustomHostnamesResult {
    hostname: IAppHostnamesColumns["hostname"];
    /** The custom hostname this row is projected onto at the edge. Absent for a platform hostname, which the wildcard already covers. */
    cloudflare_id: IAppHostnamesColumns["cloudflare_id"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
}

/** Result of query `SelectDisposableAppHostnames`. */
export interface ISelectDisposableAppHostnamesResult {
    hostname: IAppHostnamesColumns["hostname"];
    kind: IAppHostnamesColumns["kind"];
    /** The custom hostname this row is projected onto at the edge. Absent for a platform hostname, which the wildcard already covers. */
    cloudflare_id: IAppHostnamesColumns["cloudflare_id"];
}

/** Result of query `DeleteDisposableAppHostname`. */
export interface IDeleteDisposableAppHostnameResult {
    hostname: IAppHostnamesColumns["hostname"];
}

/** Result of query `SelectAppOwnership`. */
export interface ISelectAppOwnershipResult {
    id: IAppsColumns["id"];
}

/** Result of query `InsertApp`. */
export interface IInsertAppResult {
    id: IAppsColumns["id"];
}

/** Result of query `InsertAppConfig`. */
export interface IInsertAppConfigResult {
    id: IAppConfigsColumns["id"];
}

/** Result of query `InsertAppHostname`. */
export interface IInsertAppHostnameResult {
    hostname: IAppHostnamesColumns["hostname"];
    kind: IAppHostnamesColumns["kind"];
    state: IAppHostnamesColumns["state"];
    /** What the owner points _acme-challenge at, so the edge can renew the certificate without asking them again. Absent for a platform hostname. */
    dcv_target: IAppHostnamesColumns["dcv_target"];
}

/** Result of query `SelectCreatedApp`. */
export interface ISelectCreatedAppResult {
    id: IAppsColumns["id"];
    owner_id: IAppsColumns["owner_id"];
    slug: IAppsColumns["slug"];
    state: IAppsColumns["state"];
    activation: IAppsColumns["activation"];
    idle_timeout_ms: IAppsColumns["idle_timeout_ms"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: IAppsColumns["updated_at"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_total_bytes: IAppUsageColumns["volume_total_bytes"];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_used_bytes: IAppUsageColumns["volume_used_bytes"];
    /** When the guest was asked how full its filesystem was, not when the report carrying it arrived. */
    volume_measured_at: IAppUsageColumns["volume_measured_at"];
    /** MemTotal, which reads under the memory the app was allocated. A bigint, so it arrives as a string. */
    memory_total_bytes: IAppUsageColumns["memory_total_bytes"];
    /** MemTotal less MemAvailable, so cache the kernel would hand back is not counted as spent. */
    memory_used_bytes: IAppUsageColumns["memory_used_bytes"];
    /** The mean share of the vCPUs spent computing over the interval ending at compute_measured_at. */
    cpu_share: IAppUsageColumns["cpu_share"];
    /** When the guest was asked what it was spending, not when the report carrying it arrived. */
    compute_measured_at: IAppUsageColumns["compute_measured_at"];
}

/** Result of query `SelectAppsByOwner`. */
export interface ISelectAppsByOwnerResult {
    id: IAppsColumns["id"];
    owner_id: IAppsColumns["owner_id"];
    slug: IAppsColumns["slug"];
    state: IAppsColumns["state"];
    activation: IAppsColumns["activation"];
    idle_timeout_ms: IAppsColumns["idle_timeout_ms"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: IAppsColumns["updated_at"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_total_bytes: IAppUsageColumns["volume_total_bytes"];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_used_bytes: IAppUsageColumns["volume_used_bytes"];
    /** When the guest was asked how full its filesystem was, not when the report carrying it arrived. */
    volume_measured_at: IAppUsageColumns["volume_measured_at"];
    /** MemTotal, which reads under the memory the app was allocated. A bigint, so it arrives as a string. */
    memory_total_bytes: IAppUsageColumns["memory_total_bytes"];
    /** MemTotal less MemAvailable, so cache the kernel would hand back is not counted as spent. */
    memory_used_bytes: IAppUsageColumns["memory_used_bytes"];
    /** The mean share of the vCPUs spent computing over the interval ending at compute_measured_at. */
    cpu_share: IAppUsageColumns["cpu_share"];
    /** When the guest was asked what it was spending, not when the report carrying it arrived. */
    compute_measured_at: IAppUsageColumns["compute_measured_at"];
}

/** Result of query `SelectAppById`. */
export interface ISelectAppByIdResult {
    id: IAppsColumns["id"];
    owner_id: IAppsColumns["owner_id"];
    slug: IAppsColumns["slug"];
    state: IAppsColumns["state"];
    activation: IAppsColumns["activation"];
    idle_timeout_ms: IAppsColumns["idle_timeout_ms"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: IAppsColumns["updated_at"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_total_bytes: IAppUsageColumns["volume_total_bytes"];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_used_bytes: IAppUsageColumns["volume_used_bytes"];
    /** When the guest was asked how full its filesystem was, not when the report carrying it arrived. */
    volume_measured_at: IAppUsageColumns["volume_measured_at"];
    /** MemTotal, which reads under the memory the app was allocated. A bigint, so it arrives as a string. */
    memory_total_bytes: IAppUsageColumns["memory_total_bytes"];
    /** MemTotal less MemAvailable, so cache the kernel would hand back is not counted as spent. */
    memory_used_bytes: IAppUsageColumns["memory_used_bytes"];
    /** The mean share of the vCPUs spent computing over the interval ending at compute_measured_at. */
    cpu_share: IAppUsageColumns["cpu_share"];
    /** When the guest was asked what it was spending, not when the report carrying it arrived. */
    compute_measured_at: IAppUsageColumns["compute_measured_at"];
}

/** Result of query `SelectAppForConfigUpdate`. */
export interface ISelectAppForConfigUpdateResult {
    id: IAppsColumns["id"];
}

/** Result of query `SelectCurrentAppConfig`. */
export interface ISelectCurrentAppConfigResult {
    id: IAppConfigsColumns["id"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
}

/** Result of query `InsertPatchedAppConfig`. */
export interface IInsertPatchedAppConfigResult {
    id: IAppConfigsColumns["id"];
}

/** Result of query `TouchAppAfterConfigPatch`. */
export interface ITouchAppAfterConfigPatchResult {
    id: IAppsColumns["id"];
    owner_id: IAppsColumns["owner_id"];
    slug: IAppsColumns["slug"];
    state: IAppsColumns["state"];
    activation: IAppsColumns["activation"];
    idle_timeout_ms: IAppsColumns["idle_timeout_ms"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: IAppsColumns["updated_at"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_total_bytes: IAppUsageColumns["volume_total_bytes"];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_used_bytes: IAppUsageColumns["volume_used_bytes"];
    /** When the guest was asked how full its filesystem was, not when the report carrying it arrived. */
    volume_measured_at: IAppUsageColumns["volume_measured_at"];
    /** MemTotal, which reads under the memory the app was allocated. A bigint, so it arrives as a string. */
    memory_total_bytes: IAppUsageColumns["memory_total_bytes"];
    /** MemTotal less MemAvailable, so cache the kernel would hand back is not counted as spent. */
    memory_used_bytes: IAppUsageColumns["memory_used_bytes"];
    /** The mean share of the vCPUs spent computing over the interval ending at compute_measured_at. */
    cpu_share: IAppUsageColumns["cpu_share"];
    /** When the guest was asked what it was spending, not when the report carrying it arrived. */
    compute_measured_at: IAppUsageColumns["compute_measured_at"];
}

/** Result of query `SelectFinishableDeletion`. */
export interface ISelectFinishableDeletionResult {
    app_id: IAppsColumns["id"];
}

/** Result of query `SelectFinishableDeletions`. */
export interface ISelectFinishableDeletionsResult {
    app_id: IAppsColumns["id"];
}

/** Result of query `FinishDeletingApp`. */
export interface IFinishDeletingAppResult {
    id: IAppsColumns["id"];
}

/** Result of query `SelectPurgeableApps`. */
export interface ISelectPurgeableAppsResult {
    app_id: IAppsColumns["id"];
}

/** Result of query `SelectUnsharedArtifactKeys`. */
export interface ISelectUnsharedArtifactKeysResult {
    /** Where the verified bytes came to rest, so absent while they are still in a staging slot. Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: NonNullable<IArtifactsColumns["object_key"]>;
}

/** Result of query `SelectExportKeysByApp`. */
export interface ISelectExportKeysByAppResult {
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: IExportsColumns["object_key"];
}

/** Result of query `DeleteExportsByApp`. */
export interface IDeleteExportsByAppResult {
}

/** Result of query `DeleteDeploymentsByApp`. */
export interface IDeleteDeploymentsByAppResult {
}

/** Result of query `DeleteArtifactsByApp`. */
export interface IDeleteArtifactsByAppResult {
}

/** Result of query `DeleteAppUsageByApp`. */
export interface IDeleteAppUsageByAppResult {
}

/** Result of query `SelectAppAfterStateChange`. */
export interface ISelectAppAfterStateChangeResult {
    id: IAppsColumns["id"];
    owner_id: IAppsColumns["owner_id"];
    slug: IAppsColumns["slug"];
    state: IAppsColumns["state"];
    activation: IAppsColumns["activation"];
    idle_timeout_ms: IAppsColumns["idle_timeout_ms"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: IAppsColumns["updated_at"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_total_bytes: IAppUsageColumns["volume_total_bytes"];
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_used_bytes: IAppUsageColumns["volume_used_bytes"];
    /** When the guest was asked how full its filesystem was, not when the report carrying it arrived. */
    volume_measured_at: IAppUsageColumns["volume_measured_at"];
    /** MemTotal, which reads under the memory the app was allocated. A bigint, so it arrives as a string. */
    memory_total_bytes: IAppUsageColumns["memory_total_bytes"];
    /** MemTotal less MemAvailable, so cache the kernel would hand back is not counted as spent. */
    memory_used_bytes: IAppUsageColumns["memory_used_bytes"];
    /** The mean share of the vCPUs spent computing over the interval ending at compute_measured_at. */
    cpu_share: IAppUsageColumns["cpu_share"];
    /** When the guest was asked what it was spending, not when the report carrying it arrived. */
    compute_measured_at: IAppUsageColumns["compute_measured_at"];
}

/** Result of query `InsertPendingArtifact`. */
export interface IInsertPendingArtifactResult {
    id: IArtifactsColumns["id"];
    app_id: IArtifactsColumns["app_id"];
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: IArtifactsColumns["original_file_name"];
    original_file_url: IArtifactsColumns["original_file_url"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
}

/** Result of query `CompleteArtifact`. */
export interface ICompleteArtifactResult {
    id: IArtifactsColumns["id"];
    app_id: IArtifactsColumns["app_id"];
    /** Absent until the api has hashed the uploaded object; its presence is what makes the row an artifact. */
    digest: NonNullable<IArtifactsColumns["digest"]>;
    /** Counted off the uploaded bytes, so absent until they are there. A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: NonNullable<IArtifactsColumns["size_bytes"]>;
    /** Where the verified bytes came to rest, so absent while they are still in a staging slot. Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: NonNullable<IArtifactsColumns["object_key"]>;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: IArtifactsColumns["original_file_name"];
    original_file_url: IArtifactsColumns["original_file_url"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
}

/** Result of query `DeleteArtifact`. */
export interface IDeleteArtifactResult {
}

/** Result of query `SelectPendingArtifact`. */
export interface ISelectPendingArtifactResult {
    id: IArtifactsColumns["id"];
    app_id: IArtifactsColumns["app_id"];
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: IArtifactsColumns["original_file_name"];
    original_file_url: IArtifactsColumns["original_file_url"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
}

/** Result of query `SelectAbandonedArtifacts`. */
export interface ISelectAbandonedArtifactsResult {
    id: IArtifactsColumns["id"];
    app_id: IArtifactsColumns["app_id"];
}

/** Result of query `DeleteAbandonedArtifact`. */
export interface IDeleteAbandonedArtifactResult {
}

/** Result of query `SelectArtifactsByApp`. */
export interface ISelectArtifactsByAppResult {
    id: IArtifactsColumns["id"];
    app_id: IArtifactsColumns["app_id"];
    /** Absent until the api has hashed the uploaded object; its presence is what makes the row an artifact. */
    digest: NonNullable<IArtifactsColumns["digest"]>;
    /** Counted off the uploaded bytes, so absent until they are there. A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: NonNullable<IArtifactsColumns["size_bytes"]>;
    /** Where the verified bytes came to rest, so absent while they are still in a staging slot. Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: NonNullable<IArtifactsColumns["object_key"]>;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: IArtifactsColumns["original_file_name"];
    original_file_url: IArtifactsColumns["original_file_url"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
}

/** Result of query `SelectArtifactById`. */
export interface ISelectArtifactByIdResult {
    id: IArtifactsColumns["id"];
    app_id: IArtifactsColumns["app_id"];
    /** Absent until the api has hashed the uploaded object; its presence is what makes the row an artifact. */
    digest: NonNullable<IArtifactsColumns["digest"]>;
    /** Counted off the uploaded bytes, so absent until they are there. A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: NonNullable<IArtifactsColumns["size_bytes"]>;
    /** Where the verified bytes came to rest, so absent while they are still in a staging slot. Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: NonNullable<IArtifactsColumns["object_key"]>;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: IArtifactsColumns["original_file_name"];
    original_file_url: IArtifactsColumns["original_file_url"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
}

/** Result of query `SelectDeployableArtifact`. */
export interface ISelectDeployableArtifactResult {
    id: IArtifactsColumns["id"];
}

/** Result of query `InsertDeployment`. */
export interface IInsertDeploymentResult {
    id: IDeploymentsColumns["id"];
}

/** Result of query `SelectDeploymentToReplay`. */
export interface ISelectDeploymentToReplayResult {
    id: IDeploymentsColumns["id"];
}

/** Result of query `InsertReplayedDeployment`. */
export interface IInsertReplayedDeploymentResult {
    id: IDeploymentsColumns["id"];
}

/** Result of query `SelectDeploymentsByApp`. */
export interface ISelectDeploymentsByAppResult {
    id: IDeploymentsColumns["id"];
    app_id: IDeploymentsColumns["app_id"];
    artifact_id: IDeploymentsColumns["artifact_id"];
    state: IDeploymentsColumns["state"];
    instance_state: IDeploymentsColumns["instance_state"];
    activated_at: IDeploymentsColumns["activated_at"];
    /** The deployment this one replays, when it was made to go back to one. */
    rollback_of_deployment_id: IDeploymentsColumns["rollback_of_deployment_id"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    /** Why the deployment is in the state it is in, as the host put it. Never the tenant's own output, which has a streaming path of its own. */
    message: IDeploymentsColumns["message"];
    started_at: IDeploymentsColumns["started_at"];
    last_healthy_at: IDeploymentsColumns["last_healthy_at"];
    restart_count: IDeploymentsColumns["restart_count"];
    public_ipv4: IDeploymentsColumns["public_ipv4"];
    extra_public_port: IDeploymentsColumns["extra_public_port"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
}

/** Result of query `SelectDeploymentById`. */
export interface ISelectDeploymentByIdResult {
    id: IDeploymentsColumns["id"];
    app_id: IDeploymentsColumns["app_id"];
    artifact_id: IDeploymentsColumns["artifact_id"];
    state: IDeploymentsColumns["state"];
    instance_state: IDeploymentsColumns["instance_state"];
    activated_at: IDeploymentsColumns["activated_at"];
    /** The deployment this one replays, when it was made to go back to one. */
    rollback_of_deployment_id: IDeploymentsColumns["rollback_of_deployment_id"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    /** Why the deployment is in the state it is in, as the host put it. Never the tenant's own output, which has a streaming path of its own. */
    message: IDeploymentsColumns["message"];
    started_at: IDeploymentsColumns["started_at"];
    last_healthy_at: IDeploymentsColumns["last_healthy_at"];
    restart_count: IDeploymentsColumns["restart_count"];
    public_ipv4: IDeploymentsColumns["public_ipv4"];
    extra_public_port: IDeploymentsColumns["extra_public_port"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
}

/** Result of query `SelectLiveDeployments`. */
export interface ISelectLiveDeploymentsResult {
    id: IDeploymentsColumns["id"];
    state: IDeploymentsColumns["state"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    state_changed_at: IAppsColumns["updated_at"];
    desired_running: boolean;
}

/** Result of query `ApplyReportedDeployment`. */
export interface IApplyReportedDeploymentResult {
}

/** Result of query `StampDeploymentActivation`. */
export interface IStampDeploymentActivationResult {
}

/** Result of query `FailDeployment`. */
export interface IFailDeploymentResult {
}

/** Result of query `SupersedeLiveDeployment`. */
export interface ISupersedeLiveDeploymentResult {
}

/** Result of query `SelectInsertedDeployment`. */
export interface ISelectInsertedDeploymentResult {
    id: IDeploymentsColumns["id"];
    app_id: IDeploymentsColumns["app_id"];
    artifact_id: IDeploymentsColumns["artifact_id"];
    state: IDeploymentsColumns["state"];
    instance_state: IDeploymentsColumns["instance_state"];
    activated_at: IDeploymentsColumns["activated_at"];
    /** The deployment this one replays, when it was made to go back to one. */
    rollback_of_deployment_id: IDeploymentsColumns["rollback_of_deployment_id"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    /** Why the deployment is in the state it is in, as the host put it. Never the tenant's own output, which has a streaming path of its own. */
    message: IDeploymentsColumns["message"];
    started_at: IDeploymentsColumns["started_at"];
    last_healthy_at: IDeploymentsColumns["last_healthy_at"];
    restart_count: IDeploymentsColumns["restart_count"];
    public_ipv4: IDeploymentsColumns["public_ipv4"];
    extra_public_port: IDeploymentsColumns["extra_public_port"];
    http_port: IAppConfigsColumns["http_port"];
    has_extra_public_port: IAppConfigsColumns["has_extra_public_port"];
    args: IAppConfigsColumns["args"];
    vcpu_count: IAppConfigsColumns["vcpu_count"];
    memory_mib: IAppConfigsColumns["memory_mib"];
    health_check_path: IAppConfigsColumns["health_check_path"];
    health_check_interval_ms: IAppConfigsColumns["health_check_interval_ms"];
    health_check_timeout_ms: IAppConfigsColumns["health_check_timeout_ms"];
    health_check_grace_period_ms: IAppConfigsColumns["health_check_grace_period_ms"];
    health_check_healthy_threshold: IAppConfigsColumns["health_check_healthy_threshold"];
    health_check_unhealthy_threshold: IAppConfigsColumns["health_check_unhealthy_threshold"];
    restart_max_restarts: IAppConfigsColumns["restart_max_restarts"];
    restart_initial_backoff_ms: IAppConfigsColumns["restart_initial_backoff_ms"];
    restart_max_backoff_ms: IAppConfigsColumns["restart_max_backoff_ms"];
    restart_backoff_factor: IAppConfigsColumns["restart_backoff_factor"];
    restart_reset_after_ms: IAppConfigsColumns["restart_reset_after_ms"];
    environment_names: string[];
}

/** Result of query `InsertExport`. */
export interface IInsertExportResult {
    id: IExportsColumns["id"];
}

/** Result of query `SelectExportsByApp`. */
export interface ISelectExportsByAppResult {
    id: IExportsColumns["id"];
    app_id: IExportsColumns["app_id"];
    state: IExportsColumns["state"];
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: IExportsColumns["object_key"];
    size_bytes: IExportsColumns["size_bytes"];
    /** Why the export is in the state it is in, as the host put it. Never the tenant's own output. */
    message: IExportsColumns["message"];
    /** The pinned view the bundle was read from, named by the host that cut it. */
    checkpoint_id: IExportsColumns["checkpoint_id"];
    ready_at: IExportsColumns["ready_at"];
    /** When the bucket's lifecycle rule removes the bundle. The api refuses to sign past it. */
    expires_at: IExportsColumns["expires_at"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    app_slug: IAppsColumns["slug"];
}

/** Result of query `SelectExportById`. */
export interface ISelectExportByIdResult {
    id: IExportsColumns["id"];
    app_id: IExportsColumns["app_id"];
    state: IExportsColumns["state"];
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: IExportsColumns["object_key"];
    size_bytes: IExportsColumns["size_bytes"];
    /** Why the export is in the state it is in, as the host put it. Never the tenant's own output. */
    message: IExportsColumns["message"];
    /** The pinned view the bundle was read from, named by the host that cut it. */
    checkpoint_id: IExportsColumns["checkpoint_id"];
    ready_at: IExportsColumns["ready_at"];
    /** When the bucket's lifecycle rule removes the bundle. The api refuses to sign past it. */
    expires_at: IExportsColumns["expires_at"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    app_slug: IAppsColumns["slug"];
}

/** Result of query `ApplyReportedExport`. */
export interface IApplyReportedExportResult {
}

/** Result of query `FailInFlightExports`. */
export interface IFailInFlightExportsResult {
}

/** Result of query `SelectInFlightExport`. */
export interface ISelectInFlightExportResult {
    id: IExportsColumns["id"];
    app_id: IExportsColumns["app_id"];
    state: IExportsColumns["state"];
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: IExportsColumns["object_key"];
    size_bytes: IExportsColumns["size_bytes"];
    /** Why the export is in the state it is in, as the host put it. Never the tenant's own output. */
    message: IExportsColumns["message"];
    /** The pinned view the bundle was read from, named by the host that cut it. */
    checkpoint_id: IExportsColumns["checkpoint_id"];
    ready_at: IExportsColumns["ready_at"];
    /** When the bucket's lifecycle rule removes the bundle. The api refuses to sign past it. */
    expires_at: IExportsColumns["expires_at"];
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    app_slug: IAppsColumns["slug"];
}

/** Result of query `SelectHealthPing`. */
export interface ISelectHealthPingResult {
    ok: number | null;
}

export interface Queries {
    SelectDesiredDeployments: ISelectDesiredDeploymentsResult;
    SelectDesiredVolumes: ISelectDesiredVolumesResult;
    SelectDesiredHostnames: ISelectDesiredHostnamesResult;
    SelectDesiredEnvironment: ISelectDesiredEnvironmentResult;
    SelectDesiredExports: ISelectDesiredExportsResult;
    SelectDesiredExportEnvironment: ISelectDesiredExportEnvironmentResult;
    SelectAppHostnamesByOwner: ISelectAppHostnamesByOwnerResult;
    SelectAppHostnamesByApp: ISelectAppHostnamesByAppResult;
    InsertCustomAppHostname: IInsertCustomAppHostnameResult;
    UpdateCustomAppHostnameEdge: IUpdateCustomAppHostnameEdgeResult;
    UpdateCustomAppHostnameState: IUpdateCustomAppHostnameStateResult;
    DeleteCustomAppHostname: IDeleteCustomAppHostnameResult;
    SelectPendingCustomHostnames: ISelectPendingCustomHostnamesResult;
    SelectDisposableAppHostnames: ISelectDisposableAppHostnamesResult;
    DeleteDisposableAppHostname: IDeleteDisposableAppHostnameResult;
    SelectAppOwnership: ISelectAppOwnershipResult;
    InsertApp: IInsertAppResult;
    InsertAppConfig: IInsertAppConfigResult;
    InsertAppHostname: IInsertAppHostnameResult;
    SelectCreatedApp: ISelectCreatedAppResult;
    SelectAppsByOwner: ISelectAppsByOwnerResult;
    SelectAppById: ISelectAppByIdResult;
    SelectAppForConfigUpdate: ISelectAppForConfigUpdateResult;
    SelectCurrentAppConfig: ISelectCurrentAppConfigResult;
    InsertPatchedAppConfig: IInsertPatchedAppConfigResult;
    TouchAppAfterConfigPatch: ITouchAppAfterConfigPatchResult;
    SelectFinishableDeletion: ISelectFinishableDeletionResult;
    SelectFinishableDeletions: ISelectFinishableDeletionsResult;
    FinishDeletingApp: IFinishDeletingAppResult;
    SelectPurgeableApps: ISelectPurgeableAppsResult;
    SelectUnsharedArtifactKeys: ISelectUnsharedArtifactKeysResult;
    SelectExportKeysByApp: ISelectExportKeysByAppResult;
    DeleteExportsByApp: IDeleteExportsByAppResult;
    DeleteDeploymentsByApp: IDeleteDeploymentsByAppResult;
    DeleteArtifactsByApp: IDeleteArtifactsByAppResult;
    DeleteAppUsageByApp: IDeleteAppUsageByAppResult;
    SelectAppAfterStateChange: ISelectAppAfterStateChangeResult;
    InsertPendingArtifact: IInsertPendingArtifactResult;
    CompleteArtifact: ICompleteArtifactResult;
    DeleteArtifact: IDeleteArtifactResult;
    SelectPendingArtifact: ISelectPendingArtifactResult;
    SelectAbandonedArtifacts: ISelectAbandonedArtifactsResult;
    DeleteAbandonedArtifact: IDeleteAbandonedArtifactResult;
    SelectArtifactsByApp: ISelectArtifactsByAppResult;
    SelectArtifactById: ISelectArtifactByIdResult;
    SelectDeployableArtifact: ISelectDeployableArtifactResult;
    InsertDeployment: IInsertDeploymentResult;
    SelectDeploymentToReplay: ISelectDeploymentToReplayResult;
    InsertReplayedDeployment: IInsertReplayedDeploymentResult;
    SelectDeploymentsByApp: ISelectDeploymentsByAppResult;
    SelectDeploymentById: ISelectDeploymentByIdResult;
    SelectLiveDeployments: ISelectLiveDeploymentsResult;
    ApplyReportedDeployment: IApplyReportedDeploymentResult;
    StampDeploymentActivation: IStampDeploymentActivationResult;
    FailDeployment: IFailDeploymentResult;
    SupersedeLiveDeployment: ISupersedeLiveDeploymentResult;
    SelectInsertedDeployment: ISelectInsertedDeploymentResult;
    InsertExport: IInsertExportResult;
    SelectExportsByApp: ISelectExportsByAppResult;
    SelectExportById: ISelectExportByIdResult;
    ApplyReportedExport: IApplyReportedExportResult;
    FailInFlightExports: IFailInFlightExportsResult;
    SelectInFlightExport: ISelectInFlightExportResult;
    SelectHealthPing: ISelectHealthPingResult;
}

/** Columns of `account`. */
export interface IAccountColumns {
    id: string;
    accountId: string;
    providerId: string;
    userId: string;
    accessToken: string | null;
    refreshToken: string | null;
    idToken: string | null;
    accessTokenExpiresAt: Date | null;
    refreshTokenExpiresAt: Date | null;
    scope: string | null;
    password: string | null;
    createdAt: Date;
    updatedAt: Date;
    issuer: string;
}

/** Schema of `account`. */
export interface IAccountTable {
    columns: IAccountColumns;
    relationType: (typeof schema)["account"]["_relationType"];
    indexes: keyof (typeof schema)["account"]["_indexes"];
    constraints: keyof (typeof schema)["account"]["_constraints"];
}

/** Columns of `deviceCode`. */
export interface IDeviceCodeColumns {
    id: string;
    deviceCode: string;
    userCode: string;
    userId: string | null;
    expiresAt: Date;
    status: string;
    lastPolledAt: Date | null;
    pollingInterval: number | null;
    clientId: string | null;
    scope: string | null;
}

/** Schema of `deviceCode`. */
export interface IDeviceCodeTable {
    columns: IDeviceCodeColumns;
    relationType: (typeof schema)["deviceCode"]["_relationType"];
    indexes: keyof (typeof schema)["deviceCode"]["_indexes"];
    constraints: keyof (typeof schema)["deviceCode"]["_constraints"];
}

/** Columns of `session`. */
export interface ISessionColumns {
    id: string;
    expiresAt: Date;
    token: string;
    createdAt: Date;
    updatedAt: Date;
    ipAddress: string | null;
    userAgent: string | null;
    userId: string;
}

/** Schema of `session`. */
export interface ISessionTable {
    columns: ISessionColumns;
    relationType: (typeof schema)["session"]["_relationType"];
    indexes: keyof (typeof schema)["session"]["_indexes"];
    constraints: keyof (typeof schema)["session"]["_constraints"];
}

/** Columns of `user`. */
export interface IUserColumns {
    id: string;
    name: string;
    email: string;
    emailVerified: boolean;
    image: string | null;
    createdAt: Date;
    updatedAt: Date;
}

/** Schema of `user`. */
export interface IUserTable {
    columns: IUserColumns;
    relationType: (typeof schema)["user"]["_relationType"];
    indexes: keyof (typeof schema)["user"]["_indexes"];
    constraints: keyof (typeof schema)["user"]["_constraints"];
}

/** Columns of `verification`. */
export interface IVerificationColumns {
    id: string;
    identifier: string;
    value: string;
    expiresAt: Date;
    createdAt: Date;
    updatedAt: Date;
}

/** Schema of `verification`. */
export interface IVerificationTable {
    columns: IVerificationColumns;
    relationType: (typeof schema)["verification"]["_relationType"];
    indexes: keyof (typeof schema)["verification"]["_indexes"];
    constraints: keyof (typeof schema)["verification"]["_constraints"];
}

/** Columns of `app_config_environment`. */
export interface IAppConfigEnvironmentColumns {
    id: string;
    config_id: string;
    name: string;
    /** Sealed by the api before it arrives. Never written or read in the clear. */
    value: string;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
}

/** Schema of `app_config_environment`. */
export interface IAppConfigEnvironmentTable {
    columns: IAppConfigEnvironmentColumns;
    relationType: (typeof schema)["app_config_environment"]["_relationType"];
    indexes: keyof (typeof schema)["app_config_environment"]["_indexes"];
    constraints: keyof (typeof schema)["app_config_environment"]["_constraints"];
}

/** Columns of `app_configs`. */
export interface IAppConfigsColumns {
    id: string;
    app_id: import("@repo/protocol").AppId;
    http_port: import("@repo/protocol").HttpPort;
    args: string[];
    vcpu_count: number;
    memory_mib: number;
    health_check_path: string | null;
    health_check_interval_ms: number;
    health_check_timeout_ms: number;
    health_check_grace_period_ms: number;
    health_check_healthy_threshold: number;
    health_check_unhealthy_threshold: number;
    restart_max_restarts: number;
    restart_initial_backoff_ms: number;
    restart_max_backoff_ms: number;
    restart_backoff_factor: number;
    restart_reset_after_ms: number;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    has_extra_public_port: boolean;
}

/** Schema of `app_configs`. */
export interface IAppConfigsTable {
    columns: IAppConfigsColumns;
    relationType: (typeof schema)["app_configs"]["_relationType"];
    indexes: keyof (typeof schema)["app_configs"]["_indexes"];
    constraints: keyof (typeof schema)["app_configs"]["_constraints"];
}

/** Columns of `app_configs_with_environment`. */
export interface IAppConfigsWithEnvironmentColumns {
    id: string | null;
    app_id: string | null;
    http_port: number | null;
    args: string[] | null;
    vcpu_count: number | null;
    memory_mib: number | null;
    health_check_path: string | null;
    health_check_interval_ms: number | null;
    health_check_timeout_ms: number | null;
    health_check_grace_period_ms: number | null;
    health_check_healthy_threshold: number | null;
    health_check_unhealthy_threshold: number | null;
    restart_max_restarts: number | null;
    restart_initial_backoff_ms: number | null;
    restart_max_backoff_ms: number | null;
    restart_backoff_factor: number | null;
    restart_reset_after_ms: number | null;
    created_at: Date | null;
    has_extra_public_port: boolean | null;
    /** Names of the variables this config version runs with, never their values. */
    environment_names: string[] | null;
}

/** Schema of `app_configs_with_environment`. */
export interface IAppConfigsWithEnvironmentTable {
    columns: IAppConfigsWithEnvironmentColumns;
    relationType: (typeof schema)["app_configs_with_environment"]["_relationType"];
    indexes: keyof (typeof schema)["app_configs_with_environment"]["_indexes"];
    constraints: keyof (typeof schema)["app_configs_with_environment"]["_constraints"];
}

/** Columns of `app_hostnames`. */
export interface IAppHostnamesColumns {
    id: string;
    app_id: import("@repo/protocol").AppId;
    hostname: import("@repo/protocol").Hostname;
    kind: import("@repo/protocol").AppHostnameKind;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    state: import("@repo/protocol").AppHostnameState;
    /** The custom hostname this row is projected onto at the edge. Absent for a platform hostname, which the wildcard already covers. */
    cloudflare_id: string | null;
    /** What the owner points _acme-challenge at, so the edge can renew the certificate without asking them again. Absent for a platform hostname. */
    dcv_target: string | null;
}

/** Schema of `app_hostnames`. */
export interface IAppHostnamesTable {
    columns: IAppHostnamesColumns;
    relationType: (typeof schema)["app_hostnames"]["_relationType"];
    indexes: keyof (typeof schema)["app_hostnames"]["_indexes"];
    constraints: keyof (typeof schema)["app_hostnames"]["_constraints"];
}

/** Columns of `app_usage`. */
export interface IAppUsageColumns {
    id: string;
    app_id: import("@repo/protocol").AppId;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_total_bytes: string | null;
    /** A Postgres bigint, so it arrives as a string; the wire type is a number. */
    volume_used_bytes: string | null;
    /** When the guest was asked how full its filesystem was, not when the report carrying it arrived. */
    volume_measured_at: Date | null;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    /** MemTotal, which reads under the memory the app was allocated. A bigint, so it arrives as a string. */
    memory_total_bytes: string | null;
    /** MemTotal less MemAvailable, so cache the kernel would hand back is not counted as spent. */
    memory_used_bytes: string | null;
    /** The mean share of the vCPUs spent computing over the interval ending at compute_measured_at. */
    cpu_share: number | null;
    /** When the guest was asked what it was spending, not when the report carrying it arrived. */
    compute_measured_at: Date | null;
}

/** Schema of `app_usage`. */
export interface IAppUsageTable {
    columns: IAppUsageColumns;
    relationType: (typeof schema)["app_usage"]["_relationType"];
    indexes: keyof (typeof schema)["app_usage"]["_indexes"];
    constraints: keyof (typeof schema)["app_usage"]["_constraints"];
}

/** Columns of `apps`. */
export interface IAppsColumns {
    id: import("@repo/protocol").AppId;
    owner_id: import("@repo/protocol").OwnerId;
    slug: import("@repo/protocol").DnsLabel;
    state: import("@repo/protocol").AppState;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    activation: import("@repo/protocol").AppActivation;
    idle_timeout_ms: number;
}

/** Schema of `apps`. */
export interface IAppsTable {
    columns: IAppsColumns;
    relationType: (typeof schema)["apps"]["_relationType"];
    indexes: keyof (typeof schema)["apps"]["_indexes"];
    constraints: keyof (typeof schema)["apps"]["_constraints"];
}

/** Columns of `artifacts`. */
export interface IArtifactsColumns {
    id: import("@repo/protocol").ArtifactId;
    app_id: import("@repo/protocol").AppId;
    /** Absent until the api has hashed the uploaded object; its presence is what makes the row an artifact. */
    digest: import("@repo/protocol").Sha256Digest | null;
    /** Counted off the uploaded bytes, so absent until they are there. A Postgres bigint, so it arrives as a string; the wire type is a number. */
    size_bytes: string | null;
    /** Where the verified bytes came to rest, so absent while they are still in a staging slot. Key within ARTIFACTS_BUCKET; which bucket is deploy configuration. */
    object_key: import("@repo/protocol").ObjectKey | null;
    /** The name the binary was uploaded under; a content-addressed key carries none. */
    original_file_name: import("@repo/protocol").Filename;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    original_file_url: string | null;
}

/** Schema of `artifacts`. */
export interface IArtifactsTable {
    columns: IArtifactsColumns;
    relationType: (typeof schema)["artifacts"]["_relationType"];
    indexes: keyof (typeof schema)["artifacts"]["_indexes"];
    constraints: keyof (typeof schema)["artifacts"]["_constraints"];
}

/** Columns of `deployments`. */
export interface IDeploymentsColumns {
    id: import("@repo/protocol").DeploymentId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    /** The app config version this deployment was launched with. */
    config_id: string;
    /** The deployment this one replays, when it was made to go back to one. */
    rollback_of_deployment_id: import("@repo/protocol").DeploymentId | null;
    state: import("@repo/protocol").DeploymentState;
    host_port: import("@repo/protocol").HostPort | null;
    guest_ipv4: import("@repo/protocol").Ipv4Address | null;
    restart_count: number;
    /** Why the deployment is in the state it is in, as the host put it. Never the tenant's own output, which has a streaming path of its own. */
    message: string | null;
    started_at: Date | null;
    last_healthy_at: Date | null;
    activated_at: Date | null;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    public_ipv4: import("@repo/protocol").Ipv4Address | null;
    extra_public_port: import("@repo/protocol").HostPort | null;
    instance_state: import("@repo/protocol").InstanceState | null;
}

/** Schema of `deployments`. */
export interface IDeploymentsTable {
    columns: IDeploymentsColumns;
    relationType: (typeof schema)["deployments"]["_relationType"];
    indexes: keyof (typeof schema)["deployments"]["_indexes"];
    constraints: keyof (typeof schema)["deployments"]["_constraints"];
}

/** Columns of `desired_deployments`. */
export interface IDesiredDeploymentsColumns {
    id: string | null;
    app_id: string | null;
    state: string | null;
    digest: string | null;
    size_bytes: string | null;
    object_key: string | null;
    original_file_name: string | null;
    http_port: number | null;
    args: string[] | null;
    vcpu_count: number | null;
    memory_mib: number | null;
    health_check_path: string | null;
    health_check_interval_ms: number | null;
    health_check_timeout_ms: number | null;
    health_check_grace_period_ms: number | null;
    health_check_healthy_threshold: number | null;
    health_check_unhealthy_threshold: number | null;
    restart_max_restarts: number | null;
    restart_initial_backoff_ms: number | null;
    restart_max_backoff_ms: number | null;
    restart_backoff_factor: number | null;
    restart_reset_after_ms: number | null;
    config_id: string | null;
    has_extra_public_port: boolean | null;
    activation: string | null;
    idle_timeout_ms: number | null;
}

/** Schema of `desired_deployments`. */
export interface IDesiredDeploymentsTable {
    columns: IDesiredDeploymentsColumns;
    relationType: (typeof schema)["desired_deployments"]["_relationType"];
    indexes: keyof (typeof schema)["desired_deployments"]["_indexes"];
    constraints: keyof (typeof schema)["desired_deployments"]["_constraints"];
}

/** Columns of `desired_environment`. */
export interface IDesiredEnvironmentColumns {
    deployment_id: string | null;
    name: string | null;
    value: string | null;
}

/** Schema of `desired_environment`. */
export interface IDesiredEnvironmentTable {
    columns: IDesiredEnvironmentColumns;
    relationType: (typeof schema)["desired_environment"]["_relationType"];
    indexes: keyof (typeof schema)["desired_environment"]["_indexes"];
    constraints: keyof (typeof schema)["desired_environment"]["_constraints"];
}

/** Columns of `desired_export_environment`. */
export interface IDesiredExportEnvironmentColumns {
    export_id: string | null;
    name: string | null;
    value: string | null;
}

/** Schema of `desired_export_environment`. */
export interface IDesiredExportEnvironmentTable {
    columns: IDesiredExportEnvironmentColumns;
    relationType: (typeof schema)["desired_export_environment"]["_relationType"];
    indexes: keyof (typeof schema)["desired_export_environment"]["_indexes"];
    constraints: keyof (typeof schema)["desired_export_environment"]["_constraints"];
}

/** Columns of `desired_exports`. */
export interface IDesiredExportsColumns {
    id: string | null;
    app_id: string | null;
    object_key: string | null;
    state: string | null;
    digest: string | null;
    size_bytes: string | null;
    artifact_object_key: string | null;
    original_file_name: string | null;
    config_id: string | null;
}

/** Schema of `desired_exports`. */
export interface IDesiredExportsTable {
    columns: IDesiredExportsColumns;
    relationType: (typeof schema)["desired_exports"]["_relationType"];
    indexes: keyof (typeof schema)["desired_exports"]["_indexes"];
    constraints: keyof (typeof schema)["desired_exports"]["_constraints"];
}

/** Columns of `desired_hostnames`. */
export interface IDesiredHostnamesColumns {
    app_id: string | null;
    hostname: string | null;
    kind: string | null;
}

/** Schema of `desired_hostnames`. */
export interface IDesiredHostnamesTable {
    columns: IDesiredHostnamesColumns;
    relationType: (typeof schema)["desired_hostnames"]["_relationType"];
    indexes: keyof (typeof schema)["desired_hostnames"]["_indexes"];
    constraints: keyof (typeof schema)["desired_hostnames"]["_constraints"];
}

/** Columns of `desired_volumes`. */
export interface IDesiredVolumesColumns {
    app_id: string | null;
    state: string | null;
}

/** Schema of `desired_volumes`. */
export interface IDesiredVolumesTable {
    columns: IDesiredVolumesColumns;
    relationType: (typeof schema)["desired_volumes"]["_relationType"];
    indexes: keyof (typeof schema)["desired_volumes"]["_indexes"];
    constraints: keyof (typeof schema)["desired_volumes"]["_constraints"];
}

/** Columns of `exports`. */
export interface IExportsColumns {
    id: import("@repo/protocol").ExportId;
    app_id: import("@repo/protocol").AppId;
    artifact_id: import("@repo/protocol").ArtifactId;
    state: import("@repo/protocol").ExportState;
    /** Where the host writes the bundle and the api signs its download URL. */
    object_key: import("@repo/protocol").ObjectKey;
    size_bytes: string | null;
    /** Why the export is in the state it is in, as the host put it. Never the tenant's own output. */
    message: string | null;
    ready_at: Date | null;
    /** When the bucket's lifecycle rule removes the bundle. The api refuses to sign past it. */
    expires_at: Date;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
    /** The pinned view the bundle was read from, named by the host that cut it. */
    checkpoint_id: import("@repo/protocol").CheckpointId | null;
    /** The config version whose environment belongs in the bundle, pinned when the export was asked for. */
    config_id: string | null;
}

/** Schema of `exports`. */
export interface IExportsTable {
    columns: IExportsColumns;
    relationType: (typeof schema)["exports"]["_relationType"];
    indexes: keyof (typeof schema)["exports"]["_indexes"];
    constraints: keyof (typeof schema)["exports"]["_constraints"];
}

/** Columns of `finishable_deletions`. */
export interface IFinishableDeletionsColumns {
    app_id: string | null;
}

/** Schema of `finishable_deletions`. */
export interface IFinishableDeletionsTable {
    columns: IFinishableDeletionsColumns;
    relationType: (typeof schema)["finishable_deletions"]["_relationType"];
    indexes: keyof (typeof schema)["finishable_deletions"]["_indexes"];
    constraints: keyof (typeof schema)["finishable_deletions"]["_constraints"];
}

/** Columns of `live_apps`. */
export interface ILiveAppsColumns {
    id: string | null;
    owner_id: string | null;
    slug: string | null;
    state: string | null;
    created_at: Date | null;
    updated_at: Date | null;
    activation: string | null;
    idle_timeout_ms: number | null;
}

/** Schema of `live_apps`. */
export interface ILiveAppsTable {
    columns: ILiveAppsColumns;
    relationType: (typeof schema)["live_apps"]["_relationType"];
    indexes: keyof (typeof schema)["live_apps"]["_indexes"];
    constraints: keyof (typeof schema)["live_apps"]["_constraints"];
}

/** Columns of `profiles`. */
export interface IProfilesColumns {
    id: string;
    owner_id: import("@repo/protocol").OwnerId;
    /** Derived from the uuidv7 id; the moment the row was created. */
    created_at: Date;
    updated_at: Date;
}

/** Schema of `profiles`. */
export interface IProfilesTable {
    columns: IProfilesColumns;
    relationType: (typeof schema)["profiles"]["_relationType"];
    indexes: keyof (typeof schema)["profiles"]["_indexes"];
    constraints: keyof (typeof schema)["profiles"]["_constraints"];
}

/** Columns of `purgeable_apps`. */
export interface IPurgeableAppsColumns {
    app_id: string | null;
}

/** Schema of `purgeable_apps`. */
export interface IPurgeableAppsTable {
    columns: IPurgeableAppsColumns;
    relationType: (typeof schema)["purgeable_apps"]["_relationType"];
    indexes: keyof (typeof schema)["purgeable_apps"]["_indexes"];
    constraints: keyof (typeof schema)["purgeable_apps"]["_constraints"];
}

export const schema = {
    account: {
        _relationName: "account",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            accountId: { _columnName: "accountId", _foreignKeys: {} },
            providerId: { _columnName: "providerId", _foreignKeys: {} },
            userId: { _columnName: "userId", _foreignKeys: { account_userId_fkey: { _constraintName: "account_userId_fkey", _references: { _relationName: "user", _columnName: "id" } } } },
            accessToken: { _columnName: "accessToken", _foreignKeys: {} },
            refreshToken: { _columnName: "refreshToken", _foreignKeys: {} },
            idToken: { _columnName: "idToken", _foreignKeys: {} },
            accessTokenExpiresAt: { _columnName: "accessTokenExpiresAt", _foreignKeys: {} },
            refreshTokenExpiresAt: { _columnName: "refreshTokenExpiresAt", _foreignKeys: {} },
            scope: { _columnName: "scope", _foreignKeys: {} },
            password: { _columnName: "password", _foreignKeys: {} },
            createdAt: { _columnName: "createdAt", _foreignKeys: {} },
            updatedAt: { _columnName: "updatedAt", _foreignKeys: {} },
            issuer: { _columnName: "issuer", _foreignKeys: {} }
        },
        _indexes: {
            account_issuer_accountId_uidx: { _indexName: "account_issuer_accountId_uidx" },
            account_pkey: { _indexName: "account_pkey" },
            account_userId_idx: { _indexName: "account_userId_idx" }
        },
        _constraints: {
            account_pkey: { _constraintName: "account_pkey" },
            account_userId_fkey: { _constraintName: "account_userId_fkey" }
        }
    },
    deviceCode: {
        _relationName: "deviceCode",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            deviceCode: { _columnName: "deviceCode", _foreignKeys: {} },
            userCode: { _columnName: "userCode", _foreignKeys: {} },
            userId: { _columnName: "userId", _foreignKeys: {} },
            expiresAt: { _columnName: "expiresAt", _foreignKeys: {} },
            status: { _columnName: "status", _foreignKeys: {} },
            lastPolledAt: { _columnName: "lastPolledAt", _foreignKeys: {} },
            pollingInterval: { _columnName: "pollingInterval", _foreignKeys: {} },
            clientId: { _columnName: "clientId", _foreignKeys: {} },
            scope: { _columnName: "scope", _foreignKeys: {} }
        },
        _indexes: {
            deviceCode_deviceCode_uidx: { _indexName: "deviceCode_deviceCode_uidx" },
            deviceCode_pkey: { _indexName: "deviceCode_pkey" },
            deviceCode_userCode_uidx: { _indexName: "deviceCode_userCode_uidx" }
        },
        _constraints: {
            deviceCode_pkey: { _constraintName: "deviceCode_pkey" }
        }
    },
    session: {
        _relationName: "session",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            expiresAt: { _columnName: "expiresAt", _foreignKeys: {} },
            token: { _columnName: "token", _foreignKeys: {} },
            createdAt: { _columnName: "createdAt", _foreignKeys: {} },
            updatedAt: { _columnName: "updatedAt", _foreignKeys: {} },
            ipAddress: { _columnName: "ipAddress", _foreignKeys: {} },
            userAgent: { _columnName: "userAgent", _foreignKeys: {} },
            userId: { _columnName: "userId", _foreignKeys: { session_userId_fkey: { _constraintName: "session_userId_fkey", _references: { _relationName: "user", _columnName: "id" } } } }
        },
        _indexes: {
            session_pkey: { _indexName: "session_pkey" },
            session_token_key: { _indexName: "session_token_key" },
            session_userId_idx: { _indexName: "session_userId_idx" }
        },
        _constraints: {
            session_pkey: { _constraintName: "session_pkey" },
            session_token_key: { _constraintName: "session_token_key" },
            session_userId_fkey: { _constraintName: "session_userId_fkey" }
        }
    },
    user: {
        _relationName: "user",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            name: { _columnName: "name", _foreignKeys: {} },
            email: { _columnName: "email", _foreignKeys: {} },
            emailVerified: { _columnName: "emailVerified", _foreignKeys: {} },
            image: { _columnName: "image", _foreignKeys: {} },
            createdAt: { _columnName: "createdAt", _foreignKeys: {} },
            updatedAt: { _columnName: "updatedAt", _foreignKeys: {} }
        },
        _indexes: {
            user_email_key: { _indexName: "user_email_key" },
            user_pkey: { _indexName: "user_pkey" }
        },
        _constraints: {
            user_email_key: { _constraintName: "user_email_key" },
            user_pkey: { _constraintName: "user_pkey" }
        }
    },
    verification: {
        _relationName: "verification",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            identifier: { _columnName: "identifier", _foreignKeys: {} },
            value: { _columnName: "value", _foreignKeys: {} },
            expiresAt: { _columnName: "expiresAt", _foreignKeys: {} },
            createdAt: { _columnName: "createdAt", _foreignKeys: {} },
            updatedAt: { _columnName: "updatedAt", _foreignKeys: {} }
        },
        _indexes: {
            verification_identifier_idx: { _indexName: "verification_identifier_idx" },
            verification_pkey: { _indexName: "verification_pkey" }
        },
        _constraints: {
            verification_pkey: { _constraintName: "verification_pkey" }
        }
    },
    app_config_environment: {
        _relationName: "app_config_environment",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            config_id: { _columnName: "config_id", _foreignKeys: { app_config_environment_config_id_fkey: { _constraintName: "app_config_environment_config_id_fkey", _references: { _relationName: "app_configs", _columnName: "id" } } } },
            name: { _columnName: "name", _foreignKeys: {} },
            value: { _columnName: "value", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} }
        },
        _indexes: {
            app_config_environment_config_id_idx: { _indexName: "app_config_environment_config_id_idx" },
            app_config_environment_name_key: { _indexName: "app_config_environment_name_key" },
            app_config_environment_pkey: { _indexName: "app_config_environment_pkey" }
        },
        _constraints: {
            app_config_environment_config_id_fkey: { _constraintName: "app_config_environment_config_id_fkey" },
            app_config_environment_name_check: { _constraintName: "app_config_environment_name_check" },
            app_config_environment_name_key: { _constraintName: "app_config_environment_name_key" },
            app_config_environment_pkey: { _constraintName: "app_config_environment_pkey" }
        }
    },
    app_configs: {
        _relationName: "app_configs",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: { app_configs_app_id_fkey: { _constraintName: "app_configs_app_id_fkey", _references: { _relationName: "apps", _columnName: "id" } } } },
            http_port: { _columnName: "http_port", _foreignKeys: {} },
            args: { _columnName: "args", _foreignKeys: {} },
            vcpu_count: { _columnName: "vcpu_count", _foreignKeys: {} },
            memory_mib: { _columnName: "memory_mib", _foreignKeys: {} },
            health_check_path: { _columnName: "health_check_path", _foreignKeys: {} },
            health_check_interval_ms: { _columnName: "health_check_interval_ms", _foreignKeys: {} },
            health_check_timeout_ms: { _columnName: "health_check_timeout_ms", _foreignKeys: {} },
            health_check_grace_period_ms: { _columnName: "health_check_grace_period_ms", _foreignKeys: {} },
            health_check_healthy_threshold: { _columnName: "health_check_healthy_threshold", _foreignKeys: {} },
            health_check_unhealthy_threshold: { _columnName: "health_check_unhealthy_threshold", _foreignKeys: {} },
            restart_max_restarts: { _columnName: "restart_max_restarts", _foreignKeys: {} },
            restart_initial_backoff_ms: { _columnName: "restart_initial_backoff_ms", _foreignKeys: {} },
            restart_max_backoff_ms: { _columnName: "restart_max_backoff_ms", _foreignKeys: {} },
            restart_backoff_factor: { _columnName: "restart_backoff_factor", _foreignKeys: {} },
            restart_reset_after_ms: { _columnName: "restart_reset_after_ms", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            has_extra_public_port: { _columnName: "has_extra_public_port", _foreignKeys: {} }
        },
        _indexes: {
            app_configs_app_id_id_idx: { _indexName: "app_configs_app_id_id_idx" },
            app_configs_pkey: { _indexName: "app_configs_pkey" }
        },
        _constraints: {
            app_configs_app_id_fkey: { _constraintName: "app_configs_app_id_fkey" },
            app_configs_args_check: { _constraintName: "app_configs_args_check" },
            app_configs_health_check_grace_period_ms_check: { _constraintName: "app_configs_health_check_grace_period_ms_check" },
            app_configs_health_check_healthy_threshold_check: { _constraintName: "app_configs_health_check_healthy_threshold_check" },
            app_configs_health_check_interval_ms_check: { _constraintName: "app_configs_health_check_interval_ms_check" },
            app_configs_health_check_path_check: { _constraintName: "app_configs_health_check_path_check" },
            app_configs_health_check_timeout_ms_check: { _constraintName: "app_configs_health_check_timeout_ms_check" },
            app_configs_health_check_unhealthy_threshold_check: { _constraintName: "app_configs_health_check_unhealthy_threshold_check" },
            app_configs_http_port_check: { _constraintName: "app_configs_http_port_check" },
            app_configs_memory_mib_check: { _constraintName: "app_configs_memory_mib_check" },
            app_configs_pkey: { _constraintName: "app_configs_pkey" },
            app_configs_restart_backoff_factor_check: { _constraintName: "app_configs_restart_backoff_factor_check" },
            app_configs_restart_initial_backoff_ms_check: { _constraintName: "app_configs_restart_initial_backoff_ms_check" },
            app_configs_restart_max_backoff_ms_check: { _constraintName: "app_configs_restart_max_backoff_ms_check" },
            app_configs_restart_max_restarts_check: { _constraintName: "app_configs_restart_max_restarts_check" },
            app_configs_restart_reset_after_ms_check: { _constraintName: "app_configs_restart_reset_after_ms_check" },
            app_configs_vcpu_count_check: { _constraintName: "app_configs_vcpu_count_check" }
        }
    },
    app_configs_with_environment: {
        _relationName: "app_configs_with_environment",
        _relationType: "view",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: {} },
            http_port: { _columnName: "http_port", _foreignKeys: {} },
            args: { _columnName: "args", _foreignKeys: {} },
            vcpu_count: { _columnName: "vcpu_count", _foreignKeys: {} },
            memory_mib: { _columnName: "memory_mib", _foreignKeys: {} },
            health_check_path: { _columnName: "health_check_path", _foreignKeys: {} },
            health_check_interval_ms: { _columnName: "health_check_interval_ms", _foreignKeys: {} },
            health_check_timeout_ms: { _columnName: "health_check_timeout_ms", _foreignKeys: {} },
            health_check_grace_period_ms: { _columnName: "health_check_grace_period_ms", _foreignKeys: {} },
            health_check_healthy_threshold: { _columnName: "health_check_healthy_threshold", _foreignKeys: {} },
            health_check_unhealthy_threshold: { _columnName: "health_check_unhealthy_threshold", _foreignKeys: {} },
            restart_max_restarts: { _columnName: "restart_max_restarts", _foreignKeys: {} },
            restart_initial_backoff_ms: { _columnName: "restart_initial_backoff_ms", _foreignKeys: {} },
            restart_max_backoff_ms: { _columnName: "restart_max_backoff_ms", _foreignKeys: {} },
            restart_backoff_factor: { _columnName: "restart_backoff_factor", _foreignKeys: {} },
            restart_reset_after_ms: { _columnName: "restart_reset_after_ms", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            has_extra_public_port: { _columnName: "has_extra_public_port", _foreignKeys: {} },
            environment_names: { _columnName: "environment_names", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    app_hostnames: {
        _relationName: "app_hostnames",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: { app_hostnames_app_id_fkey: { _constraintName: "app_hostnames_app_id_fkey", _references: { _relationName: "apps", _columnName: "id" } } } },
            hostname: { _columnName: "hostname", _foreignKeys: {} },
            kind: { _columnName: "kind", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} },
            state: { _columnName: "state", _foreignKeys: {} },
            cloudflare_id: { _columnName: "cloudflare_id", _foreignKeys: {} },
            dcv_target: { _columnName: "dcv_target", _foreignKeys: {} }
        },
        _indexes: {
            app_hostnames_app_id_idx: { _indexName: "app_hostnames_app_id_idx" },
            app_hostnames_hostname_key: { _indexName: "app_hostnames_hostname_key" },
            app_hostnames_pending_idx: { _indexName: "app_hostnames_pending_idx" },
            app_hostnames_pkey: { _indexName: "app_hostnames_pkey" },
            app_hostnames_platform_idx: { _indexName: "app_hostnames_platform_idx" }
        },
        _constraints: {
            app_hostnames_app_id_fkey: { _constraintName: "app_hostnames_app_id_fkey" },
            app_hostnames_hostname_key: { _constraintName: "app_hostnames_hostname_key" },
            app_hostnames_kind_check: { _constraintName: "app_hostnames_kind_check" },
            app_hostnames_pkey: { _constraintName: "app_hostnames_pkey" },
            app_hostnames_state_check: { _constraintName: "app_hostnames_state_check" }
        }
    },
    app_usage: {
        _relationName: "app_usage",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: { volume_usage_app_id_fkey: { _constraintName: "volume_usage_app_id_fkey", _references: { _relationName: "apps", _columnName: "id" } } } },
            volume_total_bytes: { _columnName: "volume_total_bytes", _foreignKeys: {} },
            volume_used_bytes: { _columnName: "volume_used_bytes", _foreignKeys: {} },
            volume_measured_at: { _columnName: "volume_measured_at", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} },
            memory_total_bytes: { _columnName: "memory_total_bytes", _foreignKeys: {} },
            memory_used_bytes: { _columnName: "memory_used_bytes", _foreignKeys: {} },
            cpu_share: { _columnName: "cpu_share", _foreignKeys: {} },
            compute_measured_at: { _columnName: "compute_measured_at", _foreignKeys: {} }
        },
        _indexes: {
            app_usage_app_id_key: { _indexName: "app_usage_app_id_key" },
            app_usage_pkey: { _indexName: "app_usage_pkey" }
        },
        _constraints: {
            app_usage_app_id_key: { _constraintName: "app_usage_app_id_key" },
            app_usage_compute_whole: { _constraintName: "app_usage_compute_whole" },
            app_usage_cpu_share_is_a_share: { _constraintName: "app_usage_cpu_share_is_a_share" },
            app_usage_memory_within_itself: { _constraintName: "app_usage_memory_within_itself" },
            app_usage_pkey: { _constraintName: "app_usage_pkey" },
            app_usage_volume_whole: { _constraintName: "app_usage_volume_whole" },
            app_usage_volume_within_itself: { _constraintName: "app_usage_volume_within_itself" },
            volume_usage_app_id_fkey: { _constraintName: "volume_usage_app_id_fkey" }
        }
    },
    apps: {
        _relationName: "apps",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            owner_id: { _columnName: "owner_id", _foreignKeys: { apps_owner_id_fkey: { _constraintName: "apps_owner_id_fkey", _references: { _relationName: "user", _columnName: "id" } } } },
            slug: { _columnName: "slug", _foreignKeys: {} },
            state: { _columnName: "state", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} },
            activation: { _columnName: "activation", _foreignKeys: {} },
            idle_timeout_ms: { _columnName: "idle_timeout_ms", _foreignKeys: {} }
        },
        _indexes: {
            apps_deleted_idx: { _indexName: "apps_deleted_idx" },
            apps_owner_id_idx: { _indexName: "apps_owner_id_idx" },
            apps_pkey: { _indexName: "apps_pkey" },
            apps_slug_key: { _indexName: "apps_slug_key" }
        },
        _constraints: {
            apps_activation_check: { _constraintName: "apps_activation_check" },
            apps_idle_timeout_ms_check: { _constraintName: "apps_idle_timeout_ms_check" },
            apps_owner_id_fkey: { _constraintName: "apps_owner_id_fkey" },
            apps_pkey: { _constraintName: "apps_pkey" },
            apps_slug_key: { _constraintName: "apps_slug_key" },
            apps_state_check: { _constraintName: "apps_state_check" }
        }
    },
    artifacts: {
        _relationName: "artifacts",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: { artifacts_app_id_fkey: { _constraintName: "artifacts_app_id_fkey", _references: { _relationName: "apps", _columnName: "id" } } } },
            digest: { _columnName: "digest", _foreignKeys: {} },
            size_bytes: { _columnName: "size_bytes", _foreignKeys: {} },
            object_key: { _columnName: "object_key", _foreignKeys: {} },
            original_file_name: { _columnName: "original_file_name", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} },
            original_file_url: { _columnName: "original_file_url", _foreignKeys: {} }
        },
        _indexes: {
            artifacts_app_id_idx: { _indexName: "artifacts_app_id_idx" },
            artifacts_pending_idx: { _indexName: "artifacts_pending_idx" },
            artifacts_pkey: { _indexName: "artifacts_pkey" }
        },
        _constraints: {
            artifacts_app_id_fkey: { _constraintName: "artifacts_app_id_fkey" },
            artifacts_pkey: { _constraintName: "artifacts_pkey" }
        }
    },
    deployments: {
        _relationName: "deployments",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: { deployments_app_id_fkey: { _constraintName: "deployments_app_id_fkey", _references: { _relationName: "apps", _columnName: "id" } } } },
            artifact_id: { _columnName: "artifact_id", _foreignKeys: { deployments_artifact_id_fkey: { _constraintName: "deployments_artifact_id_fkey", _references: { _relationName: "artifacts", _columnName: "id" } } } },
            config_id: { _columnName: "config_id", _foreignKeys: { deployments_config_id_fkey: { _constraintName: "deployments_config_id_fkey", _references: { _relationName: "app_configs", _columnName: "id" } } } },
            rollback_of_deployment_id: { _columnName: "rollback_of_deployment_id", _foreignKeys: { deployments_rollback_of_deployment_id_fkey: { _constraintName: "deployments_rollback_of_deployment_id_fkey", _references: { _relationName: "deployments", _columnName: "id" } } } },
            state: { _columnName: "state", _foreignKeys: {} },
            host_port: { _columnName: "host_port", _foreignKeys: {} },
            guest_ipv4: { _columnName: "guest_ipv4", _foreignKeys: {} },
            restart_count: { _columnName: "restart_count", _foreignKeys: {} },
            message: { _columnName: "message", _foreignKeys: {} },
            started_at: { _columnName: "started_at", _foreignKeys: {} },
            last_healthy_at: { _columnName: "last_healthy_at", _foreignKeys: {} },
            activated_at: { _columnName: "activated_at", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} },
            public_ipv4: { _columnName: "public_ipv4", _foreignKeys: {} },
            extra_public_port: { _columnName: "extra_public_port", _foreignKeys: {} },
            instance_state: { _columnName: "instance_state", _foreignKeys: {} }
        },
        _indexes: {
            deployments_app_id_idx: { _indexName: "deployments_app_id_idx" },
            deployments_artifact_id_idx: { _indexName: "deployments_artifact_id_idx" },
            deployments_config_id_idx: { _indexName: "deployments_config_id_idx" },
            deployments_live_idx: { _indexName: "deployments_live_idx" },
            deployments_pkey: { _indexName: "deployments_pkey" },
            deployments_rollback_of_idx: { _indexName: "deployments_rollback_of_idx" }
        },
        _constraints: {
            deployments_app_id_fkey: { _constraintName: "deployments_app_id_fkey" },
            deployments_artifact_id_fkey: { _constraintName: "deployments_artifact_id_fkey" },
            deployments_config_id_fkey: { _constraintName: "deployments_config_id_fkey" },
            deployments_extra_public_port_check: { _constraintName: "deployments_extra_public_port_check" },
            deployments_instance_state_check: { _constraintName: "deployments_instance_state_check" },
            deployments_pkey: { _constraintName: "deployments_pkey" },
            deployments_rollback_of_deployment_id_fkey: { _constraintName: "deployments_rollback_of_deployment_id_fkey" },
            deployments_state_check: { _constraintName: "deployments_state_check" }
        }
    },
    desired_deployments: {
        _relationName: "desired_deployments",
        _relationType: "view",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: {} },
            state: { _columnName: "state", _foreignKeys: {} },
            digest: { _columnName: "digest", _foreignKeys: {} },
            size_bytes: { _columnName: "size_bytes", _foreignKeys: {} },
            object_key: { _columnName: "object_key", _foreignKeys: {} },
            original_file_name: { _columnName: "original_file_name", _foreignKeys: {} },
            http_port: { _columnName: "http_port", _foreignKeys: {} },
            args: { _columnName: "args", _foreignKeys: {} },
            vcpu_count: { _columnName: "vcpu_count", _foreignKeys: {} },
            memory_mib: { _columnName: "memory_mib", _foreignKeys: {} },
            health_check_path: { _columnName: "health_check_path", _foreignKeys: {} },
            health_check_interval_ms: { _columnName: "health_check_interval_ms", _foreignKeys: {} },
            health_check_timeout_ms: { _columnName: "health_check_timeout_ms", _foreignKeys: {} },
            health_check_grace_period_ms: { _columnName: "health_check_grace_period_ms", _foreignKeys: {} },
            health_check_healthy_threshold: { _columnName: "health_check_healthy_threshold", _foreignKeys: {} },
            health_check_unhealthy_threshold: { _columnName: "health_check_unhealthy_threshold", _foreignKeys: {} },
            restart_max_restarts: { _columnName: "restart_max_restarts", _foreignKeys: {} },
            restart_initial_backoff_ms: { _columnName: "restart_initial_backoff_ms", _foreignKeys: {} },
            restart_max_backoff_ms: { _columnName: "restart_max_backoff_ms", _foreignKeys: {} },
            restart_backoff_factor: { _columnName: "restart_backoff_factor", _foreignKeys: {} },
            restart_reset_after_ms: { _columnName: "restart_reset_after_ms", _foreignKeys: {} },
            config_id: { _columnName: "config_id", _foreignKeys: {} },
            has_extra_public_port: { _columnName: "has_extra_public_port", _foreignKeys: {} },
            activation: { _columnName: "activation", _foreignKeys: {} },
            idle_timeout_ms: { _columnName: "idle_timeout_ms", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    desired_environment: {
        _relationName: "desired_environment",
        _relationType: "view",
        _columns: {
            deployment_id: { _columnName: "deployment_id", _foreignKeys: {} },
            name: { _columnName: "name", _foreignKeys: {} },
            value: { _columnName: "value", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    desired_export_environment: {
        _relationName: "desired_export_environment",
        _relationType: "view",
        _columns: {
            export_id: { _columnName: "export_id", _foreignKeys: {} },
            name: { _columnName: "name", _foreignKeys: {} },
            value: { _columnName: "value", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    desired_exports: {
        _relationName: "desired_exports",
        _relationType: "view",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: {} },
            object_key: { _columnName: "object_key", _foreignKeys: {} },
            state: { _columnName: "state", _foreignKeys: {} },
            digest: { _columnName: "digest", _foreignKeys: {} },
            size_bytes: { _columnName: "size_bytes", _foreignKeys: {} },
            artifact_object_key: { _columnName: "artifact_object_key", _foreignKeys: {} },
            original_file_name: { _columnName: "original_file_name", _foreignKeys: {} },
            config_id: { _columnName: "config_id", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    desired_hostnames: {
        _relationName: "desired_hostnames",
        _relationType: "view",
        _columns: {
            app_id: { _columnName: "app_id", _foreignKeys: {} },
            hostname: { _columnName: "hostname", _foreignKeys: {} },
            kind: { _columnName: "kind", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    desired_volumes: {
        _relationName: "desired_volumes",
        _relationType: "view",
        _columns: {
            app_id: { _columnName: "app_id", _foreignKeys: {} },
            state: { _columnName: "state", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    exports: {
        _relationName: "exports",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            app_id: { _columnName: "app_id", _foreignKeys: { exports_app_id_fkey: { _constraintName: "exports_app_id_fkey", _references: { _relationName: "apps", _columnName: "id" } } } },
            artifact_id: { _columnName: "artifact_id", _foreignKeys: { exports_artifact_id_fkey: { _constraintName: "exports_artifact_id_fkey", _references: { _relationName: "artifacts", _columnName: "id" } } } },
            state: { _columnName: "state", _foreignKeys: {} },
            object_key: { _columnName: "object_key", _foreignKeys: {} },
            size_bytes: { _columnName: "size_bytes", _foreignKeys: {} },
            message: { _columnName: "message", _foreignKeys: {} },
            ready_at: { _columnName: "ready_at", _foreignKeys: {} },
            expires_at: { _columnName: "expires_at", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} },
            checkpoint_id: { _columnName: "checkpoint_id", _foreignKeys: {} },
            config_id: { _columnName: "config_id", _foreignKeys: { exports_config_id_fkey: { _constraintName: "exports_config_id_fkey", _references: { _relationName: "app_configs", _columnName: "id" } } } }
        },
        _indexes: {
            exports_app_id_idx: { _indexName: "exports_app_id_idx" },
            exports_artifact_id_idx: { _indexName: "exports_artifact_id_idx" },
            exports_in_flight_idx: { _indexName: "exports_in_flight_idx" },
            exports_pkey: { _indexName: "exports_pkey" }
        },
        _constraints: {
            exports_app_id_fkey: { _constraintName: "exports_app_id_fkey" },
            exports_artifact_id_fkey: { _constraintName: "exports_artifact_id_fkey" },
            exports_config_id_fkey: { _constraintName: "exports_config_id_fkey" },
            exports_pkey: { _constraintName: "exports_pkey" },
            exports_state_check: { _constraintName: "exports_state_check" }
        }
    },
    finishable_deletions: {
        _relationName: "finishable_deletions",
        _relationType: "view",
        _columns: {
            app_id: { _columnName: "app_id", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    live_apps: {
        _relationName: "live_apps",
        _relationType: "view",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            owner_id: { _columnName: "owner_id", _foreignKeys: {} },
            slug: { _columnName: "slug", _foreignKeys: {} },
            state: { _columnName: "state", _foreignKeys: {} },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} },
            activation: { _columnName: "activation", _foreignKeys: {} },
            idle_timeout_ms: { _columnName: "idle_timeout_ms", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    },
    profiles: {
        _relationName: "profiles",
        _relationType: "table",
        _columns: {
            id: { _columnName: "id", _foreignKeys: {} },
            owner_id: { _columnName: "owner_id", _foreignKeys: { profiles_owner_id_fkey: { _constraintName: "profiles_owner_id_fkey", _references: { _relationName: "user", _columnName: "id" } } } },
            created_at: { _columnName: "created_at", _foreignKeys: {} },
            updated_at: { _columnName: "updated_at", _foreignKeys: {} }
        },
        _indexes: {
            profiles_owner_id_key: { _indexName: "profiles_owner_id_key" },
            profiles_pkey: { _indexName: "profiles_pkey" }
        },
        _constraints: {
            profiles_owner_id_fkey: { _constraintName: "profiles_owner_id_fkey" },
            profiles_owner_id_key: { _constraintName: "profiles_owner_id_key" },
            profiles_pkey: { _constraintName: "profiles_pkey" }
        }
    },
    purgeable_apps: {
        _relationName: "purgeable_apps",
        _relationType: "view",
        _columns: {
            app_id: { _columnName: "app_id", _foreignKeys: {} }
        },
        _indexes: {},
        _constraints: {}
    }
} as const;

export interface Tables {
    account: IAccountTable;
    deviceCode: IDeviceCodeTable;
    session: ISessionTable;
    user: IUserTable;
    verification: IVerificationTable;
    app_config_environment: IAppConfigEnvironmentTable;
    app_configs: IAppConfigsTable;
    app_configs_with_environment: IAppConfigsWithEnvironmentTable;
    app_hostnames: IAppHostnamesTable;
    app_usage: IAppUsageTable;
    apps: IAppsTable;
    artifacts: IArtifactsTable;
    deployments: IDeploymentsTable;
    desired_deployments: IDesiredDeploymentsTable;
    desired_environment: IDesiredEnvironmentTable;
    desired_export_environment: IDesiredExportEnvironmentTable;
    desired_exports: IDesiredExportsTable;
    desired_hostnames: IDesiredHostnamesTable;
    desired_volumes: IDesiredVolumesTable;
    exports: IExportsTable;
    finishable_deletions: IFinishableDeletionsTable;
    live_apps: ILiveAppsTable;
    profiles: IProfilesTable;
    purgeable_apps: IPurgeableAppsTable;
}

declare module "@ilbertt/bun-sqlgen" {
    interface QueryResults extends Queries {
    }
    interface DatabaseTables extends Tables {
    }
}

export {};
