/* Everything /instance.env can be, and everything it must not be. The file is
 * generated by the host agent, so each rejection here is a bug this catches on the
 * console instead of inside a tenant's process. */

#include <stdio.h>
#include <string.h>

#include "../src/config.h"
#include "expect.h"

#define PORT_KEY "NIBRUN_PORT=8080\n"
#define BACKOFF_FACTOR_KEY "NIBRUN_BACKOFF_FACTOR=2\n"
#define OTHER_RESTART_KEYS          \
  "NIBRUN_MAX_RESTARTS=5\n"         \
  "NIBRUN_INITIAL_BACKOFF_MS=500\n" \
  "NIBRUN_MAX_BACKOFF_MS=30000\n"   \
  "NIBRUN_RESET_AFTER_MS=60000\n"
#define REQUIRED PORT_KEY BACKOFF_FACTOR_KEY OTHER_RESTART_KEYS

static char buffer[CONFIG_MAX_BYTES];

static bool parse(struct instance_config *config, const char *text) {
  size_t length = strlen(text);
  memcpy(buffer, text, length);
  return config_parse(config, buffer, length);
}

static bool rejects(const char *text) {
  struct instance_config config;
  return !parse(&config, text);
}

static const char *value_of(char *const *environment, const char *name) {
  size_t length = strlen(name);
  for (size_t index = 0; environment[index] != NULL; index++) {
    if (strncmp(environment[index], name, length) == 0 && environment[index][length] == '=') {
      return environment[index] + length + 1;
    }
  }
  return NULL;
}

static void accepts_a_generated_file(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED
                "NIBRUN_DNS=1.1.1.1,8.8.8.8\n"
                "ENV_DATABASE_URL=postgres://user:pa=ss@host/db\n"
                "ENV_EMPTY=\n"
                "ENV__private9= spaced value \n"));

  EXPECT(config.port == 8080);
  EXPECT(config.restart_policy.max_restarts == 5);
  EXPECT(config.restart_policy.initial_backoff_ms == 500);
  EXPECT(config.restart_policy.max_backoff_ms == 30000);
  EXPECT(config.restart_policy.backoff_factor == 2.0);
  EXPECT(config.restart_policy.reset_after_ms == 60000);

  EXPECT(config.nameserver_count == 2);
  EXPECT(strcmp(config.nameservers[0], "1.1.1.1") == 0);
  EXPECT(strcmp(config.nameservers[1], "8.8.8.8") == 0);

  EXPECT(config.tenant_variable_count == 3);
  EXPECT(strcmp(config.tenant_environment[0], "DATABASE_URL=postgres://user:pa=ss@host/db") == 0);
  EXPECT(strcmp(config.tenant_environment[1], "EMPTY=") == 0);
  EXPECT(strcmp(config.tenant_environment[2], "_private9= spaced value ") == 0);
}

static void accepts_a_file_without_a_trailing_newline(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED "ENV_LAST=value"));
  EXPECT(config.tenant_variable_count == 1);
  EXPECT(strcmp(config.tenant_environment[0], "LAST=value") == 0);
}

static void accepts_a_fractional_backoff_factor(void) {
  struct instance_config config;
  EXPECT(parse(&config, "NIBRUN_PORT=3000\n"
                        "NIBRUN_MAX_RESTARTS=0\n"
                        "NIBRUN_INITIAL_BACKOFF_MS=0\n"
                        "NIBRUN_MAX_BACKOFF_MS=0\n"
                        "NIBRUN_BACKOFF_FACTOR=1.5\n"
                        "NIBRUN_RESET_AFTER_MS=0\n"));
  EXPECT(config.restart_policy.backoff_factor == 1.5);
}

/* The name the platform issued, and the one thing here a tenant binary needs in order
 * to address itself. Optional, so a host may adopt this image before the agent that
 * writes it. */
static void carries_the_hostname_to_the_tenant(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED "NIBRUN_HOSTNAME=my-app.nibrun.app\n"));

  const char *issued = value_of(config_build_environment(&config), "NIBRUN_HOSTNAME");
  EXPECT(issued != NULL && strcmp(issued, "my-app.nibrun.app") == 0);

  EXPECT(parse(&config, REQUIRED));
  EXPECT(config.hostname == NULL);
  EXPECT(value_of(config_build_environment(&config), "NIBRUN_HOSTNAME") == NULL);
}

/* Their own would name an instance nobody is served by, and the prefix cannot keep the
 * two apart here: both reach execve under the one name. */
static void drops_a_tenant_hostname(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED "NIBRUN_HOSTNAME=mine.nibrun.app\n"
                                 "ENV_NIBRUN_HOSTNAME=elsewhere.example\n"));

  char *const *environment = config_build_environment(&config);
  EXPECT(strcmp(value_of(environment, "NIBRUN_HOSTNAME"), "mine.nibrun.app") == 0);

  size_t count = 0;
  while (environment[count] != NULL) {
    count++;
  }
  EXPECT(count == 4); /* PORT, NIBRUN_HOSTNAME, HOME, TMPDIR */
}

/* The only way a tenant value is not passed through byte for byte, and what a binary
 * configured by its own variable names rather than by ours is reached with. */
static void expands_a_runtime_reference(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED "NIBRUN_HOSTNAME=my-app.nibrun.app\n"
                                 "ENV_BARE=$NIBRUN_PORT\n"
                                 "ENV_BRACED=${NIBRUN_PORT}\n"
                                 "ENV_WITHIN=http://$NIBRUN_HOSTNAME:${NIBRUN_PORT}/health\n"
                                 "ENV_TWICE=$NIBRUN_PORT-$NIBRUN_PORT\n"
                                 "ENV_ADJACENT=${NIBRUN_PORT}0\n"));

  char *const *environment = config_build_environment(&config);
  EXPECT(strcmp(value_of(environment, "BARE"), "8080") == 0);
  EXPECT(strcmp(value_of(environment, "BRACED"), "8080") == 0);
  EXPECT(strcmp(value_of(environment, "WITHIN"), "http://my-app.nibrun.app:8080/health") == 0);
  EXPECT(strcmp(value_of(environment, "TWICE"), "8080-8080") == 0);
  /* Braces are the whole reason there are two forms: without them this names PORT0. */
  EXPECT(strcmp(value_of(environment, "ADJACENT"), "80800") == 0);
}

/* Every other '$' belongs to whoever set the value: a bcrypt hash and a password that
 * happens to read like a shell variable reach the tenant exactly as they were typed. */
static void leaves_every_other_dollar_alone(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED "ENV_HASH=$2b$12$sQ8Rn0eXm3kZpLtYvWuAiO\n"
                                 "ENV_SHELLISH=$HOME/$PATH:${FOO}\n"
                                 "ENV_DOUBLED=$$\n"
                                 "ENV_TRAILING=the cost is $\n"));

  char *const *environment = config_build_environment(&config);
  EXPECT(strcmp(value_of(environment, "HASH"), "$2b$12$sQ8Rn0eXm3kZpLtYvWuAiO") == 0);
  EXPECT(strcmp(value_of(environment, "SHELLISH"), "$HOME/$PATH:${FOO}") == 0);
  EXPECT(strcmp(value_of(environment, "DOUBLED"), "$$") == 0);
  EXPECT(strcmp(value_of(environment, "TRAILING"), "the cost is $") == 0);
}

/* A reference nobody can answer fails the boot rather than reaching the tenant as
 * itself, where it would read as a value somebody meant to write. */
static void rejects_a_reference_it_cannot_answer(void) {
  EXPECT(rejects(REQUIRED "ENV_A=$NIBRUN_NOTHING\n"));
  EXPECT(rejects(REQUIRED "ENV_A=$NIBRUN_PORT0\n"));
  EXPECT(rejects(REQUIRED "ENV_A=${NIBRUN_PORT\n"));
  /* Offered, but this instance was issued no hostname. */
  EXPECT(rejects(REQUIRED "ENV_A=$NIBRUN_HOSTNAME\n"));
  /* The supervisor's own, and never handed to a tenant. */
  EXPECT(rejects(REQUIRED "ENV_A=$NIBRUN_MAX_RESTARTS\n"));
}

static void rejects_an_expansion_that_does_not_fit(void) {
  static char text[CONFIG_MAX_BYTES];
  size_t used = (size_t)snprintf(text, sizeof(text), "%sNIBRUN_HOSTNAME=", REQUIRED);
  for (int index = 0; index < CONFIG_MAX_HOSTNAME; index++) {
    text[used++] = 'a';
  }
  used += (size_t)snprintf(text + used, sizeof(text) - used, "\nENV_LONG=");
  /* Enough copies of the longest value there is to outgrow the arena. */
  for (size_t copy = 0; copy <= CONFIG_MAX_EXPANDED_BYTES / CONFIG_MAX_HOSTNAME; copy++) {
    used += (size_t)snprintf(text + used, sizeof(text) - used, "${NIBRUN_HOSTNAME}");
  }
  text[used++] = '\n';
  text[used] = '\0';
  EXPECT(rejects(text));
}

static void accepts_an_ipv6_nameserver(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED "NIBRUN_DNS=2606:4700:4700::1111\n"));
  EXPECT(config.nameserver_count == 1);
}

static void rejects_a_broken_file(void) {
  EXPECT(rejects("NIBRUN_MAX_RESTARTS=5\n")); /* missing everything else */
  EXPECT(rejects(REQUIRED "NIBRUN_SOMETHING_NEW=1\n"));
  EXPECT(rejects(REQUIRED "NIBRUN_PORT=8081\n"));
  EXPECT(rejects(REQUIRED "PATH=/usr/bin\n"));
  EXPECT(rejects(REQUIRED "ENV_A=1\nENV_A=2\n"));
  EXPECT(rejects(REQUIRED "ENV_1LEADING_DIGIT=x\n"));
  EXPECT(rejects(REQUIRED "ENV_WITH-DASH=x\n"));
  EXPECT(rejects(REQUIRED "ENV_=x\n"));
  EXPECT(rejects(REQUIRED "ENV_NO_EQUALS\n"));
  EXPECT(rejects(REQUIRED "NIBRUN_DNS=not-an-address\n"));
  EXPECT(rejects(REQUIRED "NIBRUN_DNS=\n"));
  EXPECT(rejects(REQUIRED "NIBRUN_DNS=1.1.1.1,8.8.8.8,9.9.9.9,1.0.0.1\n"));
  EXPECT(rejects(REQUIRED "NIBRUN_HOSTNAME=\n"));
}

static void rejects_a_hostname_that_does_not_fit(void) {
  static char text[CONFIG_MAX_BYTES];
  size_t used = (size_t)snprintf(text, sizeof(text), "%sNIBRUN_HOSTNAME=", REQUIRED);
  for (int index = 0; index <= CONFIG_MAX_HOSTNAME; index++) {
    text[used++] = 'a';
  }
  text[used++] = '\n';
  text[used] = '\0';
  EXPECT(rejects(text));
}

static void rejects_a_value_that_is_not_a_number(void) {
  EXPECT(rejects("NIBRUN_PORT=0\n" BACKOFF_FACTOR_KEY OTHER_RESTART_KEYS));
  EXPECT(rejects("NIBRUN_PORT=65536\n" BACKOFF_FACTOR_KEY OTHER_RESTART_KEYS));
  EXPECT(rejects("NIBRUN_PORT=80a\n" BACKOFF_FACTOR_KEY OTHER_RESTART_KEYS));
  EXPECT(rejects("NIBRUN_PORT= 80\n" BACKOFF_FACTOR_KEY OTHER_RESTART_KEYS));
  EXPECT(rejects("NIBRUN_PORT=-1\n" BACKOFF_FACTOR_KEY OTHER_RESTART_KEYS));
  EXPECT(rejects("NIBRUN_PORT=\n" BACKOFF_FACTOR_KEY OTHER_RESTART_KEYS));
  EXPECT(rejects(PORT_KEY "NIBRUN_BACKOFF_FACTOR=0.5\n" OTHER_RESTART_KEYS));
  EXPECT(rejects(PORT_KEY "NIBRUN_BACKOFF_FACTOR=nan\n" OTHER_RESTART_KEYS));
}

/* A value carrying a newline cannot be represented in this format. What matters is
 * that the boot fails rather than the tenant receiving a truncated secret. */
static void rejects_a_value_containing_a_newline(void) {
  EXPECT(rejects(REQUIRED "ENV_SECRET=first\nsecond\n"));
  EXPECT(rejects(REQUIRED "ENV_SECRET=value\r\n"));
}

static void rejects_a_nul_byte(void) {
  struct instance_config config;
  static const char text[] = REQUIRED "ENV_SECRET=va\0lue\n";
  memcpy(buffer, text, sizeof(text) - 1);
  EXPECT(!config_parse(&config, buffer, sizeof(text) - 1));
}

static void rejects_too_many_tenant_variables(void) {
  struct instance_config config;
  static char text[CONFIG_MAX_BYTES];
  size_t used = (size_t)snprintf(text, sizeof(text), "%s", REQUIRED);
  for (int index = 0; index <= CONFIG_MAX_TENANT_VARIABLES; index++) {
    used += (size_t)snprintf(text + used, sizeof(text) - used, "ENV_VARIABLE_%d=value\n", index);
  }
  memcpy(buffer, text, used);
  EXPECT(!config_parse(&config, buffer, used));
}

static void builds_the_tenant_environment(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED "ENV_HOME=/somewhere\nENV_PORT=9999\nENV_TOKEN=abc\n"));

  char *const *environment = config_build_environment(&config);
  EXPECT(strcmp(value_of(environment, "PORT"), "8080") == 0);
  EXPECT(strcmp(value_of(environment, "HOME"), "/somewhere") == 0);
  EXPECT(strcmp(value_of(environment, "TOKEN"), "abc") == 0);
  EXPECT(strcmp(value_of(environment, "TMPDIR"), "/tmp") == 0);

  size_t count = 0;
  while (environment[count] != NULL) {
    count++;
  }
  EXPECT(count == 4); /* PORT, HOME, TOKEN, TMPDIR — the tenant's own PORT dropped */
}

/* A binary that needs a subcommand cannot be started without these, and an argv
 * that is subtly wrong is worse than one that fails: it runs the wrong thing. */
static void passes_arguments_through_in_order(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED
                "NIBRUN_ARG_0=serve\n"
                "NIBRUN_ARG_1=--http=0.0.0.0:8090\n"
                "NIBRUN_ARG_2=--dir=/app/data/pb_data\n"));

  EXPECT(config.argument_count == 3);
  char *const *argv = config_build_argv(&config, "/mnt/artifact/server");
  EXPECT(strcmp(argv[0], "/mnt/artifact/server") == 0);
  EXPECT(strcmp(argv[1], "serve") == 0);
  /* An argument containing '=' survives: the line splits on the first one only. */
  EXPECT(strcmp(argv[2], "--http=0.0.0.0:8090") == 0);
  EXPECT(strcmp(argv[3], "--dir=/app/data/pb_data") == 0);
  EXPECT(argv[4] == NULL);
}

static void accepts_arguments_in_any_order(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED
                "NIBRUN_ARG_1=second\n"
                "NIBRUN_ARG_0=first\n"));

  char *const *argv = config_build_argv(&config, "/bin/x");
  EXPECT(strcmp(argv[1], "first") == 0);
  EXPECT(strcmp(argv[2], "second") == 0);
}

static void a_binary_with_no_arguments_is_exec_d_bare(void) {
  struct instance_config config;
  EXPECT(parse(&config, REQUIRED));

  EXPECT(config.argument_count == 0);
  char *const *argv = config_build_argv(&config, "/mnt/artifact/server");
  EXPECT(strcmp(argv[0], "/mnt/artifact/server") == 0);
  EXPECT(argv[1] == NULL);
}

static void rejects_a_gap_in_the_arguments(void) {
  /* Accepting this would shift every later argument down one and exec a command
   * line nobody wrote. */
  EXPECT(rejects(REQUIRED "NIBRUN_ARG_0=serve\n" "NIBRUN_ARG_2=--verbose\n"));
}

static void rejects_an_unusable_argument_index(void) {
  EXPECT(rejects(REQUIRED "NIBRUN_ARG_=serve\n"));
  EXPECT(rejects(REQUIRED "NIBRUN_ARG_x=serve\n"));
  EXPECT(rejects(REQUIRED "NIBRUN_ARG_0=one\n" "NIBRUN_ARG_0=two\n"));
}

int main(void) {
  accepts_a_generated_file();
  accepts_a_file_without_a_trailing_newline();
  accepts_a_fractional_backoff_factor();
  accepts_an_ipv6_nameserver();
  carries_the_hostname_to_the_tenant();
  drops_a_tenant_hostname();
  expands_a_runtime_reference();
  leaves_every_other_dollar_alone();
  rejects_a_reference_it_cannot_answer();
  rejects_an_expansion_that_does_not_fit();
  rejects_a_broken_file();
  rejects_a_value_that_is_not_a_number();
  rejects_a_hostname_that_does_not_fit();
  rejects_a_value_containing_a_newline();
  rejects_a_nul_byte();
  rejects_too_many_tenant_variables();
  builds_the_tenant_environment();
  passes_arguments_through_in_order();
  accepts_arguments_in_any_order();
  a_binary_with_no_arguments_is_exec_d_bare();
  rejects_a_gap_in_the_arguments();
  rejects_an_unusable_argument_index();
  return EXPECT_REPORT("config");
}
