/** biome-ignore-all lint/performance/noBarrelFile: index is the only allowed file where we can export other files */

// Re-exported so a consumer can `Value.Parse` a branded schema without taking its own
// dependency on the validator this package already owns.
export { AssertError, Value } from '@sinclair/typebox/value';
export {
  DESIRED_INSTANCE_STATES,
  DESIRED_PRESENCE,
  type DesiredArtifact,
  DesiredArtifactSchema,
  type DesiredCheckpoint,
  DesiredCheckpointSchema,
  type DesiredExport,
  DesiredExportSchema,
  type DesiredInstance,
  DesiredInstanceSchema,
  type DesiredInstanceState,
  DesiredInstanceStateSchema,
  type DesiredPresence,
  DesiredPresenceSchema,
  type DesiredVolume,
  DesiredVolumeSchema,
  type HostDesiredState,
  HostDesiredStateSchema,
  IdleTimeoutMsSchema,
  MIN_IDLE_TIMEOUT_MS,
} from '#control/desired-state.ts';
export {
  type FilesystemQuery,
  type FilesystemQueryRequest,
  FilesystemQueryRequestSchema,
  type FilesystemQueryResponse,
  FilesystemQueryResponseSchema,
  type FilesystemQueryResult,
  FilesystemQueryResultSchema,
  FilesystemQuerySchema,
} from '#control/filesystem-query.ts';
export {
  type HostReportedState,
  HostReportedStateSchema,
  type ReportedCheckpoint,
  ReportedCheckpointSchema,
  type ReportedExport,
  ReportedExportSchema,
  type ReportedInstance,
  ReportedInstanceSchema,
  type ReportedVolume,
  ReportedVolumeSchema,
} from '#control/reported-state.ts';
export {
  type AgentPollSettings,
  AgentPollSettingsSchema,
  type AgentSession,
  type AgentSessionRequest,
  AgentSessionRequestSchema,
  AgentSessionSchema,
  DEFAULT_AGENT_POLL_SETTINGS,
} from '#control/session.ts';
export {
  AGENT_API_PREFIX,
  AGENT_ROUTES,
  type DesiredStateRequest,
  DesiredStateRequestSchema,
  type DesiredStateResponse,
  DesiredStateResponseSchema,
  PROTOCOL_VERSION,
  PROTOCOL_VERSION_HEADER,
} from '#control/transport.ts';
export {
  APP_ACTIVATIONS,
  APP_HOSTNAME_KINDS,
  APP_HOSTNAME_STATES,
  APP_STATES,
  type App,
  type AppActivation,
  AppActivationSchema,
  type AppConfig,
  AppConfigSchema,
  type AppHostname,
  type AppHostnameKind,
  AppHostnameKindSchema,
  AppHostnameSchema,
  type AppHostnameState,
  AppHostnameStateSchema,
  AppSchema,
  type AppState,
  AppStateSchema,
  EXTRA_PUBLIC_PORT_VALUES,
  interpolableRuntimeValue,
  MIN_HOSTNAMES,
  namesExtraPublicPortValues,
  namesOfferedRuntimeValues,
  OWNED_APP_STATES,
  type OwnedAppState,
  OwnedAppStateSchema,
  RUNTIME_VALUE_NAMES,
  RUNTIME_VALUES,
  type RuntimeValue,
  type RuntimeValueName,
  type TenantArguments,
  TenantArgumentsSchema,
  type TenantEnvironment,
  type TenantEnvironmentPatch,
  TenantEnvironmentPatchSchema,
  TenantEnvironmentSchema,
} from '#domain/app.ts';
export {
  type Artifact,
  ArtifactSchema,
} from '#domain/artifact.ts';
export {
  CHECKPOINT_STATES,
  type Checkpoint,
  CheckpointSchema,
  type CheckpointState,
  CheckpointStateSchema,
} from '#domain/checkpoint.ts';
export { type ComputeUsage, ComputeUsageSchema } from '#domain/compute.ts';
export {
  DEPLOYMENT_STATES,
  type Deployment,
  DeploymentSchema,
  type DeploymentState,
  DeploymentStateSchema,
} from '#domain/deployment.ts';
export {
  EXPORT_STATES,
  type Export,
  ExportSchema,
  type ExportState,
  ExportStateSchema,
} from '#domain/export.ts';
export {
  DIRECTORY_ENTRY_LIMIT,
  type DirectoryListing,
  DirectoryListingSchema,
  FILESYSTEM_ENTRY_KINDS,
  type FilesystemEntry,
  type FilesystemEntryKind,
  FilesystemEntryKindSchema,
  FilesystemEntryNameSchema,
  FilesystemEntrySchema,
  type FilesystemUsage,
  FilesystemUsageSchema,
  GUEST_PATH_ROOT,
  type GuestPath,
  GuestPathSchema,
} from '#domain/filesystem.ts';
export {
  HOST_STATES,
  type Host,
  type HostCapacity,
  HostCapacitySchema,
  HostSchema,
  type HostState,
  HostStateSchema,
  type HostVersions,
  HostVersionsSchema,
} from '#domain/host.ts';
export {
  type AppId,
  AppIdSchema,
  type ArtifactId,
  ArtifactIdSchema,
  type CheckpointId,
  CheckpointIdSchema,
  type DeploymentId,
  DeploymentIdSchema,
  type ExportId,
  ExportIdSchema,
  type FilesystemQueryId,
  FilesystemQueryIdSchema,
  type HostId,
  HostIdSchema,
  type OwnerId,
  OwnerIdSchema,
  type VolumeId,
  VolumeIdSchema,
} from '#domain/identifiers.ts';
export {
  DEFAULT_HEALTH_CHECK,
  DEFAULT_INSTANCE_RESOURCES,
  DEFAULT_RESTART_POLICY,
  type HealthCheck,
  HealthCheckSchema,
  INSTANCE_STATES,
  type InstanceResources,
  InstanceResourcesSchema,
  type InstanceState,
  InstanceStateSchema,
  type RestartPolicy,
  RestartPolicySchema,
} from '#domain/instance.ts';
export {
  DEFAULT_LOG_TIMERANGE,
  LOG_SOURCES,
  LOG_STREAM_FIELDS,
  LOG_TIMERANGE_PATTERN,
  type LogSource,
  LogSourceSchema,
  type LogTimerange,
  LogTimerangeSchema,
  SeenTenantLogs,
  TENANT_LOG_STREAMS,
  type TenantLogRecord,
  TenantLogRecordSchema,
  type TenantLogStream,
  TenantLogStreamSchema,
} from '#domain/log.ts';
export {
  DEFAULT_VOLUME_SIZE_BYTES,
  VOLUME_STATES,
  type Volume,
  VolumeSchema,
  type VolumeState,
  VolumeStateSchema,
} from '#domain/volume.ts';
export type { Brand } from '#lib/brand.ts';
export { REDACTED, redactSecrets, type SecretString, SecretStringSchema } from '#lib/secret.ts';
export {
  isValidMessage,
  type ProtocolIssue,
  ProtocolValidationError,
  parseMessage,
} from '#lib/validate.ts';
export {
  ByteSizeSchema,
  DEFAULT_HTTP_PORT,
  type DnsLabel,
  DnsLabelSchema,
  type Filename,
  FilenameSchema,
  type Hostname,
  HostnameSchema,
  type HostPort,
  HostPortSchema,
  type HttpPort,
  HttpPortSchema,
  type Ipv4Address,
  Ipv4AddressSchema,
  MAX_DNS_LABEL_LENGTH,
  type ObjectKey,
  ObjectKeySchema,
  type Sha256Digest,
  Sha256DigestSchema,
  StateMessageSchema,
  type Timestamp,
  TimestampSchema,
} from '#lib/wire.ts';
