#ifndef NIBRUN_CONFIG_H
#define NIBRUN_CONFIG_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* /instance.env, from the config drive. Line-oriented KEY=VALUE, generated by the
 * host agent, never hand-edited. Two namespaces and nothing else:
 *
 *   NIBRUN_<KEY>=<value>   what the runtime itself needs
 *   ENV_<NAME>=<value>     one of the tenant's own environment variables
 *
 * The prefixes exist so the two can never collide: a tenant variable actually
 * called NIBRUN_PORT arrives as ENV_NIBRUN_PORT and stays the tenant's.
 *
 * A tenant value may name a runtime one it is handed: `$NIBRUN_PORT` and
 * `${NIBRUN_PORT}` both expand, and a name this runtime does not offer fails the
 * boot rather than reaching the tenant as itself. Nothing else expands, so a secret
 * holding `$`, `$$` or `$HOME` arrives byte for byte — the prefix is what keeps the
 * substitution off values it was never meant for. The cost is that a value holding a
 * literal `$NIBRUN_` has no representation, which is the bargain the format already
 * makes for one holding a newline.
 *
 * The runtime carries no defaults for any of it. DEFAULT_RESTART_POLICY in
 * packages/protocol is the only place those values exist; the agent resolves them
 * and writes them out, so a missing key is a bug in the writer and is reported as
 * one rather than papered over. */

#define CONFIG_MAX_BYTES (128 * 1024)
/* Only a value naming a runtime one is copied here, so this bounds what interpolation
 * may add rather than the file it adds to. */
#define CONFIG_MAX_EXPANDED_BYTES CONFIG_MAX_BYTES
/* Mirrors MAX_HOSTNAME_LENGTH in packages/protocol, which refuses to write a longer one. */
#define CONFIG_MAX_HOSTNAME 253
#define CONFIG_MAX_TENANT_VARIABLES 256
/* Mirrors MAX_ARGUMENTS in packages/protocol, which refuses to write more. */
#define CONFIG_MAX_ARGUMENTS 64
/* glibc's resolver reads at most MAXNS entries and silently drops the rest. */
#define CONFIG_MAX_NAMESERVERS 3

struct restart_policy {
  uint32_t max_restarts;
  uint32_t initial_backoff_ms;
  uint32_t max_backoff_ms;
  double backoff_factor;
  uint32_t reset_after_ms;
};

struct instance_config {
  uint32_t port;
  /* The hostname nibrun issued the app, handed to the tenant so a binary can build
   * its own absolute URLs. NULL when the writer sent none, which is what lets a host
   * adopt this image before the agent that writes it — every other key here is
   * required, and an agent older than the image would fail every boot. */
  char *hostname;
  struct restart_policy restart_policy;
  char *nameservers[CONFIG_MAX_NAMESERVERS];
  size_t nameserver_count;
  /* argv[1..]; argv[0] is the binary itself, which the runtime owns. Arrives as
   * NIBRUN_ARG_<n> from 0 upwards, numbered rather than delimited because a
   * format with no quoting cannot carry a separator an argument might contain. */
  char *arguments[CONFIG_MAX_ARGUMENTS];
  size_t argument_count;
  /* "NAME=value" strings, ready for execve. */
  char *tenant_environment[CONFIG_MAX_TENANT_VARIABLES];
  size_t tenant_variable_count;
};

/* Parses in place: every string in `config` points into `text`, which is modified
 * and needs one writable byte at text[length] for the last line's terminator. The
 * exception is a tenant value that named a runtime one, which cannot be written back
 * over the reference it grew out of and points into storage of this module's instead.
 * Reports the first thing it rejects and returns false — never a partial config. */
bool config_parse(struct instance_config *config, char *text, size_t length);

bool config_read_file(struct instance_config *config, const char *path, char *buffer, size_t buffer_size);

/* argv for execve: the binary, then the parsed arguments, then NULL. */
char *const *config_build_argv(const struct instance_config *config, const char *executable);

/* The environment the tenant is exec'd with: PORT and NIBRUN_HOSTNAME, which the
 * platform owns because they are the port the agent probes and the name the edge
 * routes to, then the tenant's own variables, then defaults for anything they did
 * not set. A tenant variable of either name is dropped rather than exported: it
 * would describe an instance that does not exist. */
char *const *config_build_environment(const struct instance_config *config);

#endif
