#ifndef NIBRUN_CONFIG_H
#define NIBRUN_CONFIG_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

/* /instance.env, from the config drive. Line-oriented KEY=VALUE, generated by the
 * host agent, never hand-edited. Two namespaces and nothing else:
 *
 *   NIBRUN_<KEY>=<value>   what the runtime itself needs
 *   ENV_<NAME>=<value>     one of the tenant's own environment variables
 *
 * The prefixes exist so the two can never collide: a tenant variable actually
 * called NIBRUN_PORT arrives as ENV_NIBRUN_PORT and stays the tenant's.
 *
 * The runtime carries no defaults for any of it. DEFAULT_RESTART_POLICY in
 * packages/protocol is the only place those values exist; the agent resolves them
 * and writes them out, so a missing key is a bug in the writer and is reported as
 * one rather than papered over. */

#define CONFIG_MAX_BYTES (128 * 1024)
#define CONFIG_MAX_TENANT_VARIABLES 256
/* glibc's resolver reads at most MAXNS entries and silently drops the rest. */
#define CONFIG_MAX_NAMESERVERS 3

struct restart_policy {
  uint32_t max_restarts;
  uint32_t initial_backoff_ms;
  uint32_t max_backoff_ms;
  double backoff_factor;
  uint32_t reset_after_ms;
};

struct instance_config {
  uint32_t port;
  struct restart_policy restart_policy;
  char *nameservers[CONFIG_MAX_NAMESERVERS];
  size_t nameserver_count;
  /* "NAME=value" strings, ready for execve. */
  char *tenant_environment[CONFIG_MAX_TENANT_VARIABLES];
  size_t tenant_variable_count;
};

/* Parses in place: every string in `config` points into `text`, which is modified
 * and needs one writable byte at text[length] for the last line's terminator.
 * Reports the first thing it rejects and returns false — never a partial config. */
bool config_parse(struct instance_config *config, char *text, size_t length);

bool config_read_file(struct instance_config *config, const char *path, char *buffer, size_t buffer_size);

/* The environment the tenant is exec'd with: PORT, which the platform owns because
 * it is the port the agent probes and routes to, then the tenant's own variables,
 * then defaults for anything they did not set. */
char *const *config_build_environment(const struct instance_config *config);

#endif
