export const DEPLOYMENT_GRANT_TOKEN_PREFIX = 'nibrun_deploy_';
export const DEPLOYMENT_GRANT_SECRET_BYTES = 32;
export const DEPLOYMENT_GRANT_LIFETIME_MS = 600_000;
export const GITHUB_IDENTITY_TOKEN_MAX_LENGTH = 16_384;
