import { type ClassValue, clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';

// Generated by the shadcn CLI, which rewrites it whenever it reinstalls the
// `utils` registry item.

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
