/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as DeployRouteImport } from './routes/deploy'
import { Route as authDeviceRouteImport } from './routes/(auth)/device'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as dashboardIndexRouteImport } from './routes/(dashboard)/index'
import { Route as dashboardAppsIndexRouteImport } from './routes/(dashboard)/apps/index'
import { Route as dashboardAppsAppIdRouteRouteImport } from './routes/(dashboard)/apps/$appId/route'
import { Route as dashboardAppsAppIdIndexRouteImport } from './routes/(dashboard)/apps/$appId/index'
import { Route as dashboardAppsAppIdDomainsRouteImport } from './routes/(dashboard)/apps/$appId/domains'
import { Route as dashboardAppsAppIdFilesRouteImport } from './routes/(dashboard)/apps/$appId/files'
import { Route as dashboardAppsAppIdLogsRouteImport } from './routes/(dashboard)/apps/$appId/logs'

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const DeployRoute = DeployRouteImport.update({
  id: '/deploy',
  path: '/deploy',
  getParentRoute: () => rootRouteImport,
} as any)
const authDeviceRoute = authDeviceRouteImport.update({
  id: '/device',
  path: '/device',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const dashboardIndexRoute = dashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardAppsIndexRoute = dashboardAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardAppsAppIdRouteRoute = dashboardAppsAppIdRouteRouteImport.update({
  id: '/apps/$appId',
  path: '/apps/$appId',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const dashboardAppsAppIdIndexRoute = dashboardAppsAppIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => dashboardAppsAppIdRouteRoute,
} as any)
const dashboardAppsAppIdDomainsRoute =
  dashboardAppsAppIdDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => dashboardAppsAppIdRouteRoute,
  } as any)
const dashboardAppsAppIdFilesRoute = dashboardAppsAppIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => dashboardAppsAppIdRouteRoute,
} as any)
const dashboardAppsAppIdLogsRoute = dashboardAppsAppIdLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => dashboardAppsAppIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/deploy': typeof DeployRoute
  '/device': typeof authDeviceRoute
  '/login': typeof authLoginRoute
  '/': typeof dashboardIndexRoute
  '/apps/$appId': typeof dashboardAppsAppIdRouteRouteWithChildren
  '/apps/': typeof dashboardAppsIndexRoute
  '/apps/$appId/domains': typeof dashboardAppsAppIdDomainsRoute
  '/apps/$appId/files': typeof dashboardAppsAppIdFilesRoute
  '/apps/$appId/logs': typeof dashboardAppsAppIdLogsRoute
  '/apps/$appId/': typeof dashboardAppsAppIdIndexRoute
}
export interface FileRoutesByTo {
  '/deploy': typeof DeployRoute
  '/device': typeof authDeviceRoute
  '/login': typeof authLoginRoute
  '/': typeof dashboardIndexRoute
  '/apps': typeof dashboardAppsIndexRoute
  '/apps/$appId/domains': typeof dashboardAppsAppIdDomainsRoute
  '/apps/$appId/files': typeof dashboardAppsAppIdFilesRoute
  '/apps/$appId/logs': typeof dashboardAppsAppIdLogsRoute
  '/apps/$appId': typeof dashboardAppsAppIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/deploy': typeof DeployRoute
  '/(auth)/device': typeof authDeviceRoute
  '/(auth)/login': typeof authLoginRoute
  '/(dashboard)/': typeof dashboardIndexRoute
  '/(dashboard)/apps/$appId': typeof dashboardAppsAppIdRouteRouteWithChildren
  '/(dashboard)/apps/': typeof dashboardAppsIndexRoute
  '/(dashboard)/apps/$appId/domains': typeof dashboardAppsAppIdDomainsRoute
  '/(dashboard)/apps/$appId/files': typeof dashboardAppsAppIdFilesRoute
  '/(dashboard)/apps/$appId/logs': typeof dashboardAppsAppIdLogsRoute
  '/(dashboard)/apps/$appId/': typeof dashboardAppsAppIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/deploy'
    | '/device'
    | '/login'
    | '/'
    | '/apps/$appId'
    | '/apps/'
    | '/apps/$appId/domains'
    | '/apps/$appId/files'
    | '/apps/$appId/logs'
    | '/apps/$appId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/deploy'
    | '/device'
    | '/login'
    | '/'
    | '/apps'
    | '/apps/$appId/domains'
    | '/apps/$appId/files'
    | '/apps/$appId/logs'
    | '/apps/$appId'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/deploy'
    | '/(auth)/device'
    | '/(auth)/login'
    | '/(dashboard)/'
    | '/(dashboard)/apps/$appId'
    | '/(dashboard)/apps/'
    | '/(dashboard)/apps/$appId/domains'
    | '/(dashboard)/apps/$appId/files'
    | '/(dashboard)/apps/$appId/logs'
    | '/(dashboard)/apps/$appId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  DeployRoute: typeof DeployRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deploy': {
      id: '/deploy'
      path: '/deploy'
      fullPath: '/deploy'
      preLoaderRoute: typeof DeployRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/device': {
      id: '/(auth)/device'
      path: '/device'
      fullPath: '/device'
      preLoaderRoute: typeof authDeviceRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(dashboard)/': {
      id: '/(dashboard)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/apps/': {
      id: '/(dashboard)/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof dashboardAppsIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/apps/$appId': {
      id: '/(dashboard)/apps/$appId'
      path: '/apps/$appId'
      fullPath: '/apps/$appId'
      preLoaderRoute: typeof dashboardAppsAppIdRouteRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/apps/$appId/': {
      id: '/(dashboard)/apps/$appId/'
      path: '/'
      fullPath: '/apps/$appId/'
      preLoaderRoute: typeof dashboardAppsAppIdIndexRouteImport
      parentRoute: typeof dashboardAppsAppIdRouteRoute
    }
    '/(dashboard)/apps/$appId/domains': {
      id: '/(dashboard)/apps/$appId/domains'
      path: '/domains'
      fullPath: '/apps/$appId/domains'
      preLoaderRoute: typeof dashboardAppsAppIdDomainsRouteImport
      parentRoute: typeof dashboardAppsAppIdRouteRoute
    }
    '/(dashboard)/apps/$appId/files': {
      id: '/(dashboard)/apps/$appId/files'
      path: '/files'
      fullPath: '/apps/$appId/files'
      preLoaderRoute: typeof dashboardAppsAppIdFilesRouteImport
      parentRoute: typeof dashboardAppsAppIdRouteRoute
    }
    '/(dashboard)/apps/$appId/logs': {
      id: '/(dashboard)/apps/$appId/logs'
      path: '/logs'
      fullPath: '/apps/$appId/logs'
      preLoaderRoute: typeof dashboardAppsAppIdLogsRouteImport
      parentRoute: typeof dashboardAppsAppIdRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authDeviceRoute: typeof authDeviceRoute
  authLoginRoute: typeof authLoginRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authDeviceRoute: authDeviceRoute,
  authLoginRoute: authLoginRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardAppsAppIdRouteRouteChildren {
  dashboardAppsAppIdDomainsRoute: typeof dashboardAppsAppIdDomainsRoute
  dashboardAppsAppIdFilesRoute: typeof dashboardAppsAppIdFilesRoute
  dashboardAppsAppIdLogsRoute: typeof dashboardAppsAppIdLogsRoute
  dashboardAppsAppIdIndexRoute: typeof dashboardAppsAppIdIndexRoute
}

const dashboardAppsAppIdRouteRouteChildren: dashboardAppsAppIdRouteRouteChildren =
  {
    dashboardAppsAppIdDomainsRoute: dashboardAppsAppIdDomainsRoute,
    dashboardAppsAppIdFilesRoute: dashboardAppsAppIdFilesRoute,
    dashboardAppsAppIdLogsRoute: dashboardAppsAppIdLogsRoute,
    dashboardAppsAppIdIndexRoute: dashboardAppsAppIdIndexRoute,
  }

const dashboardAppsAppIdRouteRouteWithChildren =
  dashboardAppsAppIdRouteRoute._addFileChildren(
    dashboardAppsAppIdRouteRouteChildren,
  )

interface dashboardRouteRouteChildren {
  dashboardIndexRoute: typeof dashboardIndexRoute
  dashboardAppsAppIdRouteRoute: typeof dashboardAppsAppIdRouteRouteWithChildren
  dashboardAppsIndexRoute: typeof dashboardAppsIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardIndexRoute: dashboardIndexRoute,
  dashboardAppsAppIdRouteRoute: dashboardAppsAppIdRouteRouteWithChildren,
  dashboardAppsIndexRoute: dashboardAppsIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  DeployRoute: DeployRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
