/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as appsCmd } from './commands/apps.ts';
import type { command as appsDeleteCmd } from './commands/apps/delete.ts';
import type { command as appsDomainsAddHostnameCmd } from './commands/apps/domains/add/[hostname].ts';
import type { command as appsDomainsCmd } from './commands/apps/domains.ts';
import type { command as appsDomainsRemoveHostnameCmd } from './commands/apps/domains/remove/[hostname].ts';
import type { command as appsExportDestinationCmd } from './commands/apps/export/[destination].ts';
import type { command as appsFilesLsCmd } from './commands/apps/files/ls.ts';
import type { command as appsFilesLsPathCmd } from './commands/apps/files/ls/[path].ts';
import type { command as appsListCmd } from './commands/apps/list.ts';
import type { command as appsLogsCmd } from './commands/apps/logs.ts';
import type { command as appsResumeCmd } from './commands/apps/resume.ts';
import type { command as appsStatusCmd } from './commands/apps/status.ts';
import type { command as appsSuspendCmd } from './commands/apps/suspend.ts';
import type { command as appsUpdateCmd } from './commands/apps/update.ts';
import type { command as loginCmd } from './commands/login.ts';
import type { command as rootCmd } from './commands/_root.ts';
import type { command as runCommandCmd } from './commands/run/[command].ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'apps': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps delete': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps domains': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps domains add [hostname]': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
        'apps domains': { options: InferForwardedOptions<typeof appsDomainsCmd.options>; params: InferParams<typeof appsDomainsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps domains remove [hostname]': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
        'apps domains': { options: InferForwardedOptions<typeof appsDomainsCmd.options>; params: InferParams<typeof appsDomainsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps export [destination]': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps files ls': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps files ls [path]': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
        'apps files ls': { options: InferForwardedOptions<typeof appsFilesLsCmd.options>; params: InferParams<typeof appsFilesLsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps list': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps logs': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps resume': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps status': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps suspend': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'apps update': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'login': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
    'run [command]': {
      parents: {};
      rootOptions: InferForwardedOptions<typeof rootCmd.options>;
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: { path: '', load: () => import('./commands/_root.ts').then((m) => m.command) },
  literalChildren: {
    'apps': {
      segment: { kind: 'literal', value: 'apps' },
      command: { path: 'apps', load: () => import('./commands/apps.ts').then((m) => m.command) },
      literalChildren: {
        'delete': {
          segment: { kind: 'literal', value: 'delete' },
          command: { path: 'apps delete', load: () => import('./commands/apps/delete.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'domains': {
          segment: { kind: 'literal', value: 'domains' },
          command: { path: 'apps domains', load: () => import('./commands/apps/domains.ts').then((m) => m.command) },
          literalChildren: {
            'add': {
              segment: { kind: 'literal', value: 'add' },
              command: null,
              literalChildren: {},
              paramChild: {
                segment: { kind: 'param', name: 'hostname' },
                command: { path: 'apps domains add [hostname]', load: () => import('./commands/apps/domains/add/[hostname].ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
            },
            'remove': {
              segment: { kind: 'literal', value: 'remove' },
              command: null,
              literalChildren: {},
              paramChild: {
                segment: { kind: 'param', name: 'hostname' },
                command: { path: 'apps domains remove [hostname]', load: () => import('./commands/apps/domains/remove/[hostname].ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
            },
          },
          paramChild: null,
        },
        'export': {
          segment: { kind: 'literal', value: 'export' },
          command: null,
          literalChildren: {},
          paramChild: {
            segment: { kind: 'param', name: 'destination' },
            command: { path: 'apps export [destination]', load: () => import('./commands/apps/export/[destination].ts').then((m) => m.command) },
            literalChildren: {},
            paramChild: null,
          },
        },
        'files': {
          segment: { kind: 'literal', value: 'files' },
          command: null,
          literalChildren: {
            'ls': {
              segment: { kind: 'literal', value: 'ls' },
              command: { path: 'apps files ls', load: () => import('./commands/apps/files/ls.ts').then((m) => m.command) },
              literalChildren: {},
              paramChild: {
                segment: { kind: 'param', name: 'path' },
                command: { path: 'apps files ls [path]', load: () => import('./commands/apps/files/ls/[path].ts').then((m) => m.command) },
                literalChildren: {},
                paramChild: null,
              },
            },
          },
          paramChild: null,
        },
        'list': {
          segment: { kind: 'literal', value: 'list' },
          command: { path: 'apps list', load: () => import('./commands/apps/list.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'logs': {
          segment: { kind: 'literal', value: 'logs' },
          command: { path: 'apps logs', load: () => import('./commands/apps/logs.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'resume': {
          segment: { kind: 'literal', value: 'resume' },
          command: { path: 'apps resume', load: () => import('./commands/apps/resume.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'status': {
          segment: { kind: 'literal', value: 'status' },
          command: { path: 'apps status', load: () => import('./commands/apps/status.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'suspend': {
          segment: { kind: 'literal', value: 'suspend' },
          command: { path: 'apps suspend', load: () => import('./commands/apps/suspend.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
        'update': {
          segment: { kind: 'literal', value: 'update' },
          command: { path: 'apps update', load: () => import('./commands/apps/update.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'login': {
      segment: { kind: 'literal', value: 'login' },
      command: { path: 'login', load: () => import('./commands/login.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'run': {
      segment: { kind: 'literal', value: 'run' },
      command: null,
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'command' },
        command: { path: 'run [command]', load: () => import('./commands/run/[command].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
