/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as runCommandCmd } from './commands/run/[command].ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'run [command]': {
      parents: {};
      rootOptions: {};
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'run': {
      segment: { kind: 'literal', value: 'run' },
      command: null,
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'command' },
        command: { path: 'run [command]', load: () => import('./commands/run/[command].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
