/** biome-ignore-all lint/complexity/noBannedTypes: empty-object shapes are deliberate */
// AUTOGENERATED by @parshjs/codegen - do not edit by hand.
import type { InferForwardedOptions, InferParams, RuntimeNode } from '@parshjs/core';
import type { command as appsCmd } from './commands/apps.ts';
import type { command as appsLogsCmd } from './commands/apps/logs.ts';
import type { command as loginCmd } from './commands/login.ts';
import type { command as runCommandCmd } from './commands/run/[command].ts';

declare module '@parshjs/core' {
  interface CommandRegistry {
    'apps': {
      parents: {};
      rootOptions: {};
    };
    'apps logs': {
      parents: {
        'apps': { options: InferForwardedOptions<typeof appsCmd.options>; params: InferParams<typeof appsCmd.params> };
      };
      rootOptions: {};
    };
    'login': {
      parents: {};
      rootOptions: {};
    };
    'run [command]': {
      parents: {};
      rootOptions: {};
    };
  }
}

export const commandTree: RuntimeNode = {
  segment: null,
  command: null,
  literalChildren: {
    'apps': {
      segment: { kind: 'literal', value: 'apps' },
      command: { path: 'apps', load: () => import('./commands/apps.ts').then((m) => m.command) },
      literalChildren: {
        'logs': {
          segment: { kind: 'literal', value: 'logs' },
          command: { path: 'apps logs', load: () => import('./commands/apps/logs.ts').then((m) => m.command) },
          literalChildren: {},
          paramChild: null,
        },
      },
      paramChild: null,
    },
    'login': {
      segment: { kind: 'literal', value: 'login' },
      command: { path: 'login', load: () => import('./commands/login.ts').then((m) => m.command) },
      literalChildren: {},
      paramChild: null,
    },
    'run': {
      segment: { kind: 'literal', value: 'run' },
      command: null,
      literalChildren: {},
      paramChild: {
        segment: { kind: 'param', name: 'command' },
        command: { path: 'run [command]', load: () => import('./commands/run/[command].ts').then((m) => m.command) },
        literalChildren: {},
        paramChild: null,
      },
    },
  },
  paramChild: null,
};
