// Generated by scripts/generate-public-contract.ts; API definitions are the source of truth.
import { Kind, OptionalKind, Type } from '@sinclair/typebox';
import type {
  App,
  CronListing,
  Filename,
  GuestPath,
  Sha256Digest,
  TenantEnvironmentPatch,
} from '#models.ts';
export const AppNameSchema = Type.Unsafe<App['name']>({
  minLength: 1,
  maxLength: 128,
  type: 'string',
  [Kind]: 'String',
});
export const HttpPortSchema = Type.Unsafe<App['config']['httpPort']>({
  description: 'HTTP port the tenant binary listens on inside the guest.',
  minimum: 1,
  maximum: 65535,
  type: 'integer',
  [Kind]: 'Integer',
  [OptionalKind]: 'Optional',
});
export const TenantEnvironmentPatchSchema = Type.Unsafe<TenantEnvironmentPatch>({
  additionalProperties: false,
  type: 'object',
  patternProperties: {
    '^(?!__proto__$)[A-Za-z_][A-Za-z0-9_]*$': {
      anyOf: [
        {
          pattern:
            '^(?:[^$]|\\$(?!\\{NIBRUN_[A-Za-z0-9_]*\\})|\\$\\{(?:NIBRUN_DATA_DIR|NIBRUN_EXTRA_PUBLIC_PORT|NIBRUN_HOSTNAME|NIBRUN_HTTP_PORT|NIBRUN_PUBLIC_IPV4)\\})*$',
          'x-nibrun-secret': true,
          maxLength: 32768,
          type: 'string',
          [Kind]: 'String',
        },
        { type: 'null', [Kind]: 'Null' },
      ],
      [Kind]: 'Union',
    },
  },
  [Kind]: 'Record',
  [OptionalKind]: 'Optional',
});
export const FilenameSchema = Type.Unsafe<Filename>({
  description: 'One path segment, safe to use as a name inside an archive.',
  pattern: '^[0-9A-Za-z][0-9A-Za-z._-]{0,126}$',
  minLength: 1,
  maxLength: 127,
  type: 'string',
  [Kind]: 'String',
});
export const HostnameSchema = Type.Unsafe<App['hostnames'][number]['hostname']>({
  pattern: '^[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]{0,61}[a-z0-9])?)+$',
  maxLength: 253,
  type: 'string',
  [Kind]: 'String',
});
export const GuestPathSchema = Type.Unsafe<GuestPath>({
  description: 'Absolute path within a tenant volume. No `.`, no `..`, no trailing slash.',
  pattern:
    '^/(?:(?!\\.{1,2}(?:/|$))[^/\\\\"\'\\u0000-\\u001f]+(?:/(?!\\.{1,2}(?:/|$))[^/\\\\"\'\\u0000-\\u001f]+)*)?$',
  minLength: 1,
  maxLength: 4096,
  type: 'string',
  [Kind]: 'String',
  [OptionalKind]: 'Optional',
});
export const Sha256DigestSchema = Type.Unsafe<Sha256Digest>({
  description: 'Lowercase hex SHA-256, unprefixed.',
  pattern: '^[0-9a-f]{64}$',
  minLength: 64,
  maxLength: 64,
  type: 'string',
  [Kind]: 'String',
});
export const TimestampSchema = Type.Unsafe<App['createdAt']>({
  description: 'ISO 8601 instant with a mandatory UTC offset.',
  pattern: '^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,9})?(Z|[+-]\\d{2}:\\d{2})$',
  maxLength: 35,
  type: 'string',
  [Kind]: 'String',
});
export const AppIdSchema = Type.Unsafe<App['id']>({
  description: 'A tenant app, and the microVM running it.',
  pattern: '^[0-9A-Za-z][0-9A-Za-z_-]{0,62}$',
  minLength: 1,
  maxLength: 63,
  type: 'string',
  [Kind]: 'String',
});
export const CronJobIdSchema = Type.Unsafe<CronListing['jobs'][number]['jobId']>({
  description: 'One registered cron job.',
  pattern: '^[0-9A-Za-z][0-9A-Za-z_-]{0,62}$',
  minLength: 1,
  maxLength: 63,
  type: 'string',
  [Kind]: 'String',
});
export const SecretStringSchema = Type.Unsafe<string>({
  pattern:
    '^(?:[^$]|\\$(?!\\{NIBRUN_[A-Za-z0-9_]*\\})|\\$\\{(?:NIBRUN_DATA_DIR|NIBRUN_EXTRA_PUBLIC_PORT|NIBRUN_HOSTNAME|NIBRUN_HTTP_PORT|NIBRUN_PUBLIC_IPV4)\\})*$',
  'x-nibrun-secret': true,
  maxLength: 32768,
  type: 'string',
  [Kind]: 'String',
});
export const APP_STATES = ['active', 'suspended', 'deleting', 'deleted'] as const;
export const APP_ACTIVATIONS = ['always', 'on-request'] as const;
export const APP_HOSTNAME_STATES = ['pending', 'active', 'failed'] as const;
export const APP_HOSTNAME_KINDS = ['platform', 'custom'] as const;
export const DEPLOYMENT_STATES = [
  'pending',
  'starting',
  'running',
  'stopped',
  'superseded',
  'failed',
] as const;
export const INSTANCE_STATES = [
  'pending',
  'starting',
  'running',
  'unhealthy',
  'stopping',
  'stopped',
  'idle',
  'failed',
] as const;
export const TENANT_LOG_STREAMS = ['stdout', 'stderr'] as const;
export const FILESYSTEM_ENTRY_KINDS = ['file', 'directory', 'other'] as const;
export const DEFAULT_HTTP_PORT = 3000 as const;
export const DEFAULT_VOLUME_SIZE_BYTES = 8589934592 as const;
export const DEFAULT_INSTANCE_RESOURCES = { vcpuCount: 1, memoryMib: 256 } as const;
export const DEFAULT_LOG_TIMERANGE = '5m' as const;
export const LOG_TIMERANGE_PATTERN = '^[1-9][0-9]{0,3}[smh]$' as const;
export const RUNTIME_VALUES = {
  DATA_DIR: { name: 'NIBRUN_DATA_DIR', description: 'the directory the volume is mounted at' },
  EXTRA_PUBLIC_PORT: {
    name: 'NIBRUN_EXTRA_PUBLIC_PORT',
    description: 'the port to bind and announce',
  },
  HOSTNAME: { name: 'NIBRUN_HOSTNAME', description: "the app's own hostname" },
  HTTP_PORT: { name: 'NIBRUN_HTTP_PORT', description: 'the port the binary must listen on' },
  PUBLIC_IPV4: { name: 'NIBRUN_PUBLIC_IPV4', description: 'the address it is reached at' },
} as const;
export const TENANT_VALUE_PATTERN =
  '^(?:[^$]|\\$(?!\\{NIBRUN_[A-Za-z0-9_]*\\})|\\$\\{(?:NIBRUN_DATA_DIR|NIBRUN_EXTRA_PUBLIC_PORT|NIBRUN_HOSTNAME|NIBRUN_HTTP_PORT|NIBRUN_PUBLIC_IPV4)\\})*$' as const;
export const REDACTED = '[redacted]' as const;
export const CNAME_RECORD_TYPE = { name: 'CNAME', code: 5 } as const;
export const DOMAIN_DNS_RECORD_TEMPLATES = {
  routing: [{ hostname: '{hostname}', type: 'CNAME', target: '{routingTarget}' }],
  withCertificate: [
    { hostname: '{hostname}', type: 'CNAME', target: '{routingTarget}' },
    { hostname: '_acme-challenge.{hostname}', type: 'CNAME', target: '{dcvTarget}' },
  ],
} as const;
export const MIN_IDLE_TIMEOUT_MS = 60000 as const;
export const MAX_IDLE_TIMEOUT_MS = 86400000 as const;
export const DIRECTORY_ENTRY_LIMIT = 1000 as const;
export const CRON_TIME_ZONE = 'UTC' as const;
