-- Better Auth owns this table. Generated by the adapter's createSchema with the API key plugin
-- enabled in scripts/auth-schema.ts; keep its DDL diffable against regeneration.

create table "auth"."apikey" ("id" text not null primary key, "configId" text not null, "name" text, "start" text, "referenceId" text not null, "prefix" text, "key" text not null, "refillInterval" integer, "refillAmount" integer, "lastRefillAt" timestamptz, "enabled" boolean, "rateLimitEnabled" boolean, "rateLimitTimeWindow" integer, "rateLimitMax" integer, "requestCount" integer, "remaining" integer, "lastRequest" timestamptz, "expiresAt" timestamptz, "createdAt" timestamptz not null, "updatedAt" timestamptz not null, "permissions" text, "metadata" text);
create index "apikey_configId_idx" on "auth"."apikey" ("configId");
create index "apikey_referenceId_idx" on "auth"."apikey" ("referenceId");
create index "apikey_key_idx" on "auth"."apikey" ("key");
