name: build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: build:required
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - uses: ./.github/actions/prepare

      - name: Build
        run: bun run build
